/* Generated by Together */
/*
*		ID1ID(0)ID
*/
#ifndef IDENTITY_H
#define IDENTITY_H

#include "App/GameAppNet.h"

class CGameApp;

class Identity
{
	friend class CGameApp;
public:

	Identity():m_maxID(0){}

	std::uint32_t GetID()
	{
		return ++m_maxID;
	}

private:
	std::uint32_t m_maxID;
};
#endif //IDENTITY_H
