/* Generated by Together */

#ifndef SUBMAP_H
#define SUBMAP_H
#include "App/GameAppNet.h"
#include <tchar.h>
#include <stdio.h>
#include "Entity/EntitySpawn.h"
#include "World/SwitchMapRecord.h"
#include "Network/CompCommand.h"
#include "Item/Item.h"
#include "Combat/Range.h"
#include "World/EyeshotCell.h"
#include "World/StateCell.h"
#include "World/StateCellGrid.h"
#include "World/Weather.h"
#include "App/GameApp.h"
#include "World/MapRes.h"

#define defRANGE_MGRUNIU_NUM	10000

class MgrUnit;
class CActiveMgrUnitL;
class Entity;
class CFightAble;

//
class COutMapCha {
public:
	struct SMgrUnit {
		bool IsValidCha(void) {
			if (!pCCha) return false;
			return pCCha->GetID() == ulChaID;
		}

		dbc::Long lLeftTick1; //
		dbc::Long lLeftTick2; //
		dbc::Char chAction; //
		CCharacter* pCCha;
		dbc::uLong ulChaID;
		SSwitchMapInfo SwitchInfo;
		dbc::Char chStep;

		SMgrUnit* pSNext;
	};

	COutMapCha(unsigned short usFreq = 2000);
	~COutMapCha();

	void Add(CCharacter* pCObj, dbc::uLong ulChaID, SSwitchMapInfo* pSwitchInfo, dbc::Char chAction,
			 dbc::Long lLeftTick1, dbc::Long lLeftTick2);
	void Run(unsigned long ulCurTick);
	void Drop();
	void ExecTimeCha(SMgrUnit* pChaInfo);
	std::deque<std::unique_ptr<SMgrUnit>> spawnQueue; // Spawn queue rework - Mdr
private:
	unsigned long m_ulTick;
	unsigned short m_usFreq; //
};

//
class SubMap {
public:
	SubMap();
	virtual ~SubMap();

	bool Init(CMapRes* pCMapRes, dbc::Short sCopyNO = 0);

	bool         IsRun(void);
	const char*  GetName(void);

	//pt.
	Rect GetEyeshot(Point& pt) const;
	Rect GetEyeshot(short sMgrUnitX, short sMgrUnitY) const;
	void GetEyeshotCenter(Point& pt);
	Rect GetHoldStateCell(Point& pt, dbc::Long lRadius) const;
	void GetHoldStateCellCenter(Point& pt);

	void Add(Entity* ent);
	void Delete(Entity* ent);
	void MoveInStateCell(CCharacter* pCCha, const Point& SSrcPos, const Point& STarPos);
	void MoveInMapMask(CCharacter* pCCha, const Point& SSrcPos, const Point& STarPos);

	bool EnsurePos(Square* pSEntShape, Entity* ent, dbc::cLong clSearchRadius = 40 * 100);
	bool Enter(Square* pSEntShape, Entity* ent, dbc::cLong clSearchRadius = 40 * 100);
	void GoOut(Entity* ent);
	void MoveTo(Entity* pCEnt, const Point& STar);
	void RefreshEyeshot(Entity* pCEnt, bool bEyeshot, bool bHide, bool bShow);

	bool         IsValidPos(dbc::Long lPosX, dbc::Long lPosY);

	dbc::uShort  GetAreaAttr(dbc::Long lPosX, dbc::Long lPosY);
	dbc::uShort  GetAreaAttr(const Point& Pos);

	void NotiStateCellToEyeshot(dbc::Short sCellX, dbc::Short sCellY);

	//
	void BeginSearchInRange(dbc::Long* plRangeBParam, dbc::Long* plRangeEParam, bool bIncludeHideEnti = false);
	CCharacter* GetNextCharacterInRange(void);

	//
	bool RangeAddState(dbc::uChar uchFightID, dbc::uLong ulSrcWorldID, dbc::Long lSrcHandle,
					   dbc::Char chObjType, dbc::Char chObjHabitat, dbc::Char chEffType, dbc::Short* sStateParam);
	bool RangeAddState(Rect* pSRange, dbc::uChar uchFightID, dbc::uLong ulSrcWorldID, dbc::Long lSrcHandle,
					   dbc::Char chObjType, dbc::Char chObjHabitat, dbc::Char chEffType, dbc::Short* sStateParam);

	//
	CCharacter* FindCharacter(dbc::uLong ulID, const Point& point);
	//
	bool IsMoveAble(Entity* pCEnt, dbc::Long lPosX, dbc::Long lPosY);

	void LoadMonsterInfo(void);

	BOOL LoadNpc();

	BOOL LoadEventEntity();

	Corsairs::Common::NPC::CNpcRecord* GetNpcInfo(USHORT sNpcID);

	CItem* ItemSpawn(const SItemGrid* pItemInfo, dbc::Long lPosX, dbc::Long lPosY, dbc::Char chSpawnType,
					 dbc::Long lFromEntityID = 0, dbc::Long lProtChaID = 0, dbc::Long lProtChaHandle = 0,
					 dbc::Long lProtTime = 0, dbc::Long lOnTick = 0,
					 CEvent* pCEvent = NULL);
	CCharacter* ChaSpawn(dbc::Long lChaInfoID, dbc::Char chCtrlType, dbc::Short sAngle, Point* pSPos,
						 bool bEyeshotAbility = false,
						 dbc::cChar* cszChaName = 0, const long clSearchRadius = 120 * 100);

	void EntryOpen(void);
	void EntryClose(void);
	void Open(void);
	void Run(DWORD dwCurTime);
	void Close(void);
	void ClearSurfaceState(void);
	void ResetNotPlyCha(void);
	void ClearPlayerCha(void);
	void ClearAllCha(void);
	void ClearAllMonster(void);
	void ClearAllMonsterByName(const char* szMonsName);
	void Notice(const char* szString);

	dbc::Short   GetEyeshotCellWidth(void) const;
	dbc::Short   GetEyeshotCellHeight(void) const;
	dbc::Short   GetEyeshotCellLin(void) const;
	dbc::Short   GetEyeshotCellCol(void) const;

	dbc::Short   GetStateCellWidth(void) const;
	dbc::Short   GetStateCellHeight(void) const;
	dbc::Short   GetStateCellLin(void) const;
	dbc::Short   GetStateCellCol(void) const;

	dbc::Short   GetBlockCellWidth(void) const;
	dbc::Short   GetBlockCellHeight(void) const;

	bool         GetTerrainCellSize(dbc::Short* psWidth, dbc::Short* psHeight);
	bool         GetTerrainCellAttr(dbc::Short sUnitX, dbc::Short sUnitY, dbc::uShort& usAttribute);
	bool         GetTerrainCellIsland(dbc::Short sUnitX, dbc::Short sUnitY, dbc::uChar& uchIsland);

	BYTE         IsBlock(dbc::Long lCellX, dbc::Long lCellY);

	const Rect&  GetRange(void) const;

	BYTE         GetMapID();

	dbc::Short   GetEyeshotWidth(void) const;

	bool         CanPK(void);
	bool         CanSavePos(void);

	void BeforePlyOutMap(CCharacter* pCCha);
	void AfterPlyEnterMap(CCharacter* pCCha);

	dbc::Long    GetMonsterNum(void);

	CMapRes*     GetMapRes(void);

	void         SetCopyNO(dbc::Short sCopyNO);
	dbc::Short   GetCopyNO(void);

	dbc::Long    GetPlayerNum(void);

	dbc::Long    GetInfoParam(dbc::Char chParamID);
	bool         SetInfoParam(dbc::Char chParamID, dbc::Long lParamVal);

	void BeginGetPlyCha(void);
	CCharacter* GetNextPlyCha(void);
	bool CheckRun(void);
	void DealActivePlayer(std::string& function); //2006.10.12wsj.
	void DealPlayer(std::string& function);

	void         SetSpecialInter(int interva); //2006.10.12wsj

	dbc::Long    GetActivePlayer(); //2006.10.12wsj

	dbc::Long CountEyeshotPlyActiveNum(dbc::Long lCellX, dbc::Long lCellY);

	void         ActiveEyeshotCell(dbc::Long lCellX, dbc::Long lCellY);
	void         InactiveEyeshotCell(dbc::Long lCellX, dbc::Long lCellY);

	bool         IsValidStateCell(dbc::Long x, dbc::Long y);

	CChaListNode* StateCellAddCha(dbc::Long lCellX, dbc::Long lCellY, CCharacter* pCCha, bool bIn);
	void          StateCellDelCha(dbc::Long lCellX, dbc::Long lCellY, CChaListNode* pCChaNode);

	void          ActiveStateCell(dbc::Long lCellX, dbc::Long lCellY);
	void          InactiveStateCell(dbc::Long lCellX, dbc::Long lCellY);

	bool AddCellState(dbc::uChar uchFightID, dbc::uLong ulSrcWorldID, dbc::Long lSrcHandle, dbc::Char chObjType,
					  dbc::Char chObjHabitat, dbc::Char chEffType,
					  dbc::Long lCellX, dbc::Long lCellY, dbc::uChar uchStateID, dbc::uChar uchStateLv,
					  dbc::uLong ulStartTick, dbc::Long lOnTick, dbc::Char chType, dbc::Char chWithCenter);

	void          ReleaseStateCell(dbc::Long x, dbc::Long y);

	CEyeshotCell** m_pCEyeshotCell; //
	StateCellGrid _stateCellGrid; //
	COutMapCha m_COutMapCha; //
	//
	CActEyeshotCell m_CEyeshotCellL; //
	CActStateCell m_CStateCellL; //

	bool m_bIsRun; //
	CWeatherMgr m_WeatherMgr; //

private:
	CMapRes* m_pCMapRes;
	CTimer m_timeSpecialRun;

	void CheckStateCell(dbc::Long x, dbc::Long y);

	//
	struct {
		bool m_bIncludeHideEnti; //
		dbc::Short m_sRangeMgrUnitNum; //
		dbc::Long m_lRangeMgrUnit[defRANGE_MGRUNIU_NUM][2]; // x,y
		dbc::Long m_lRangeCentUnit[2]; // ;
		dbc::Short m_sRangeCurMgrUnit; //
		CChaListNode* m_pRangeCurEntiNode; //
		CRangeBase* m_pCBaseRange;

		CRangeStick m_CStickRange;
		CRangeFan m_CFanRange;
		CRangeSquare m_CSquareCRange;
		CRangeCircle m_CCircleRange;
	};

	dbc::Short m_sCopyNO;
	CTimer m_timeScriptRun;

	dbc::Long m_lPlayerNum;
	//	dbc::Long	m_lActivePlayerNum;
	dbc::Long m_lInfoParam[defMAPCOPY_INFO_PARAM_NUM];
};

#endif //SUBMAP_H
