/* Generated by Together */

#include "Core/stdafx.h"
namespace Corsairs::Common::NPC {}
using namespace Corsairs::Common::NPC;
#include "World/SubMap.h"
#include "Combat/MoveAble.h"
#include "App/GameApp.h"
#include "Core/CommFunc.h"
#include "Script/LuaAPI.h"

using namespace std;
const char* GetResPath(const char *pszRes);

SubMap::SubMap()
:m_pCEyeshotCell(0)
,m_bIsRun(false)
{
	m_sCopyNO = 0;
	m_timeSpecialRun.Begin(300*1000);//5*60*1000

}

SubMap::~SubMap()
{
}

bool SubMap::Init(CMapRes *pCMapRes, int16_t sCopyNO)
{
	m_pCMapRes = pCMapRes;
	m_pCBaseRange = 0;

	// Инициализация 2D-сетки state cell
	_stateCellGrid.Init(GetStateCellLin(), GetStateCellCol());

	// Инициализация eyeshot cell
	m_pCEyeshotCell = new CEyeshotCell*[GetEyeshotCellLin()];
	if (!m_pCEyeshotCell) {
		ThrowRuntimeError(RES_STRING(GM_SUBMAP_CPP_00002));
	}
	short	sECellSX, sECellEX, sECellSY, sECellEY;
	for (short i = 0; i < GetEyeshotCellLin(); i++)
	{
		m_pCEyeshotCell[i] = new CEyeshotCell[GetEyeshotCellCol()];
		if (!m_pCEyeshotCell[i]) {
			ThrowRuntimeError(RES_STRING(GM_SUBMAP_CPP_00002));
		}
		for (short j = 0; j < GetEyeshotCellCol(); j++)
		{
			m_pCEyeshotCell[i][j].m_sPosX = j;
			m_pCEyeshotCell[i][j].m_sPosY = i;

			sECellSX = j * GetEyeshotCellWidth() / GetStateCellWidth();
			sECellEX = (j * GetEyeshotCellWidth() + GetEyeshotCellWidth() - 1) / GetStateCellWidth();
			sECellSY = i * GetEyeshotCellHeight() / GetStateCellHeight();
			sECellEY = (i * GetEyeshotCellHeight() + GetEyeshotCellHeight() - 1) / GetStateCellHeight();

			auto& slots = m_pCEyeshotCell[i][j]._stateCellSlots;
			slots.reserve(static_cast<size_t>(sECellEX - sECellSX + 1) * (sECellEY - sECellSY + 1));
			for (short m = sECellSY; m <= sECellEY; m++) {
				for (short n = sECellSX; n <= sECellEX; n++) {
					slots.push_back(_stateCellGrid.SlotAddress(n, m));
				}
			}
		}
	}

	// 
	m_pCMapRes->m_pCMonsterSpawn->Load(this); // resok
	m_pCMapRes->m_pCMapSwitchEntitySpawn->Load(this); // resok
	LoadNpc(); // NPCNPC,resok
	LoadEventEntity(); // ,resok

	luaL_dofile(g_pLuaState, GetResPath(m_pCMapRes->m_szMonsterCofFile)); //resok

	m_bIsRun = false;
	m_sCopyNO = sCopyNO;
	m_timeScriptRun.Begin(1000);
	m_lPlayerNum = 0;
//	m_lActivePlayerNum = 0;
	memset(m_lInfoParam, 0, sizeof(std::int32_t) * defMAPCOPY_INFO_PARAM_NUM);

	return true;
}

//=============================================================================
// lFromEntityID 
// lProtChaIDlProtTime lProtChaID0.lProtTime0-1
// lOnTick 0-1
// usEventTypepEventRec 
//=============================================================================
CItem* SubMap::ItemSpawn(const SItemGrid *pItemInfo, std::int32_t lPosX, std::int32_t lPosY, char chSpawnType,
						 std::int32_t lFromEntityID, std::int32_t lProtChaID, std::int32_t lProtChaHandle, std::int32_t lProtTime, std::int32_t lOnTick,
						 CEvent	*pCEvent)
{
	CItem *pCItem;
	CItemRecord *pCItemRec;

	pCItemRec = GetItemRecordInfo(pItemInfo->sID);
	if (!pCItemRec)
		return 0;
	pCItem = g_pGameApp->GetNewItem();
	if (!pCItem)
		return 0;
	memcpy(&pCItem->m_SGridContent, pItemInfo, sizeof(SItemGrid));
	//if (pCItemRec->chExclusiveID) // ID0
	//{
	//	pItemInfo->SetDBParam(-1, 0);
	//}
	//else
	//	pItemInfo->SetDBParam(-1, 0);
	pCItem->m_pCItemRecord = pCItemRec;
	if (pCEvent)
		pCItem->SetEvent(*pCEvent);
	pCItem->SetName(pCItemRec->szName.c_str());
	pCItem->SetCat(pItemInfo->sID);
	pCItem->m_ID = g_pGameApp->m_Ident.GetID();
	pCItem->SetSpawnType(chSpawnType);
	pCItem->SetFromID(lFromEntityID);
	Corsairs::Util::Square SShape = {{lPosX, lPosY}, 0};
	pCItem->SetAngle(rand() / 360);
	pCItem->SetEyeshotAbility(false);
	if (!Enter(&SShape, pCItem))
	{
		pCItem->Free();
		return 0;
	}
	pCItem->SetSpawnType(enumITEM_APPE_NATURAL);
	pCItem->SetProtCha(lProtChaID, lProtChaHandle);
	if (lProtTime == -1)
		pCItem->SetProtOnTick(0);
	else if (lProtTime > 0)
		pCItem->SetProtOnTick(lProtTime);
	if (lOnTick == -1)
		pCItem->SetOnTick(0);
	if (lOnTick > 0)
		pCItem->SetOnTick(lOnTick);


	char szLogName[defLOG_NAME_LEN] = "";
	{
		auto _s = std::format("{}+{}", pCItem->GetName(), pCItem->GetID());
		std::strncpy(szLogName, _s.c_str(), sizeof(szLogName) - 1);
		szLogName[sizeof(szLogName) - 1] = 0;
	}
	pCItem->SetLogName(szLogName);

	return pCItem;
}

//=============================================================================
// chCtrlType CompCommand.h EChaCtrlType
//=============================================================================
CCharacter* SubMap::ChaSpawn(std::int32_t lChaInfoID, Corsairs::Common::Character::EChaCtrlType chCtrlType, int16_t sAngle, Corsairs::Util::Point *pSPos, bool bEyeshotAbility, const char *cszChaName, const long clSearchRadius)
{
	CCharacter	*pCCha;
	CChaRecord	*pCChaRecord;

	if (!IsValidPos(pSPos->X, pSPos->Y))
		return 0;

	pCChaRecord = GetChaRecordInfo(lChaInfoID);
	if (pCChaRecord == NULL)
		return 0;
	pCCha = g_pGameApp->GetNewCharacter();
	if (!pCCha)
		return 0;
	pCCha->m_CChaAttr.Init(lChaInfoID);
	if (chCtrlType == EChaCtrlType::NONE)
		chCtrlType = pCChaRecord->CtrlType;
	pCCha->setAttr(ATTR_CHATYPE, chCtrlType);
	pCCha->m_pCChaRecord = pCChaRecord;
	pCCha->SetCat((short)(pCCha->m_pCChaRecord->Id));
	pCCha->SetID(g_pGameApp->m_Ident.GetID());
	pCCha->m_AIType = (BYTE)(pCChaRecord->AiNo);
	pCCha->m_sChaseRange = (short)(pCChaRecord->CDis);
	pCCha->SetAngle(sAngle);
	Corsairs::Util::Square SShape = {*pSPos, pCCha->m_pCChaRecord->Radii};
	if (!cszChaName)
		pCCha->_name = pCCha->m_pCChaRecord->DataName;
	else
		pCCha->_name = cszChaName;
	pCCha->SetEyeshotAbility(bEyeshotAbility);
	if (pCChaRecord->Dormancy > 0)
		pCCha->SetExistState(enumEXISTS_SLEEPING);
	if (!Enter(&SShape, pCCha, clSearchRadius))
	{
		pCCha->Free();
		return 0;
	}
	Corsairs::Util::Circle l_STerritory = {*pSPos, 500};
	pCCha->SetTerritory(l_STerritory);

	// 
	pCCha->EnrichSkillBag();

	char szLogName[defLOG_NAME_LEN] = "";
	{
		auto _s = std::format("Cha-{}+{}", pCCha->GetName(), pCCha->GetID());
		std::strncpy(szLogName, _s.c_str(), sizeof(szLogName) - 1);
		szLogName[sizeof(szLogName) - 1] = 0;
	}
	pCCha->SetLogName(szLogName);

	// pCCha->ResetLifeTime(5000);
	
	return pCCha;
}

// 
void SubMap::Notice(const char *szString)
{
	//  :   
	auto WtPk = Corsairs::Net::Msg::serialize(Corsairs::Net::Msg::McSysInfoMessage{szString});

	std::vector<CPlayer*> recipients;
	CEyeshotCell	*pCEyeCell;
	CCharacter		*pCCha;
	std::int32_t			lChaCount, lChaNum;
	m_CEyeshotCellL.BeginGet();
	while (pCEyeCell = m_CEyeshotCellL.GetNext())
	{
		lChaCount = 0;
		lChaNum = pCEyeCell->GetChaNum();
		pCCha = pCEyeCell->m_pCChaL;
		while (pCCha)
		{
			if (++lChaCount > lChaNum)
			{
				//LG("", "[%d,%d] %d\n", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
				ToLogService("errors", LogLevel::Error, "eyeshot cell[{},{}]fact entity nubmer{}", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
				break;
			}

			if(pCCha->IsPlayerFocusCha())
			{
				recipients.push_back(pCCha->GetPlayer());

				if (!pCCha->GetSubMap())
					//LG("", " %s(%s)[%d,%d] \n",
					ToLogService("errors", LogLevel::Error, "in the wind map notify character {}({})[{},{}] 's map is empty",
						pCCha->GetLogName(), pCCha->GetPlyCtrlCha()->GetLogName(), pCCha->GetPos().X, pCCha->GetPos().Y);
			}

			if (pCCha->m_pCEyeshotCellNext)
				pCCha = pCCha->m_pCEyeshotCellNext->IsCharacter();
			else
				pCCha = 0;
		}
	}

	SENDTOCLIENT(WtPk, recipients);
}

std::int32_t SubMap::CountEyeshotPlyActiveNum(std::int32_t lCellX, std::int32_t lCellY)
{
	std::int32_t	lActNum = 0;

	CCharacter		*pCCha;
	std::int32_t			lChaCount = 0, lChaNum;
	pCCha = m_pCEyeshotCell[lCellY][lCellX].m_pCChaL;
	lChaNum = m_pCEyeshotCell[lCellY][lCellX].GetChaNum();
	while (pCCha)
	{
		if (++lChaCount > lChaNum)
		{
			//LG("", "[%d,%d] %d\n", lCellX, lCellY, lChaNum);
			ToLogService("errors", LogLevel::Error, "account eyeshot cell [{},{}]'s activation character numberpractice character number{}", lCellX, lCellY, lChaNum);
			break;
		}

		if(pCCha->IsPlayerCha())
		{
			if (pCCha->GetEyeshotAbility())
				lActNum++;
		}

		if (pCCha->m_pCEyeshotCellNext)
			pCCha = pCCha->m_pCEyeshotCellNext->IsCharacter();
		else
			pCCha = 0;
	}

	return lActNum;
}

// 
bool SubMap::IsMoveAble(Entity *pCEnt, std::int32_t lPosX, std::int32_t lPosY)
{
	CFightAble	*pCCha = 0;
	if (!pCEnt || !(pCCha = pCEnt->IsFightAble()))
		return false;
	return ::IsMoveAble(static_cast<EChaCtrlType>(pCCha->m_CChaAttr.GetAttr(ATTR_CHATYPE)), pCCha->m_pCChaRecord->Territory, pCEnt->GetAreaAttr()); //
}

BOOL SubMap::LoadEventEntity()
{
	g_pScriptMap = this;
	char szMapEntity[256];
	{
		auto _s = std::format("{}\\{}{}", GetName(), GetName(), "entity.lua");
		std::strncpy(szMapEntity, _s.c_str(), sizeof(szMapEntity) - 1);
		szMapEntity[sizeof(szMapEntity) - 1] = 0;
	}
	ReloadEntity( GetResPath(szMapEntity) );
	return TRUE;
}

BOOL SubMap::LoadNpc()
{
	if( m_pCMapRes->m_pNpcSpawn->Load( *this ) == -1 )
	{
		ThrowRuntimeError(RES_STRING(GM_SUBMAP_CPP_00003));
		return FALSE;
	}

	return TRUE;
}

CNpcRecord* SubMap::GetNpcInfo( USHORT sNpcID )
{
	if( m_pCMapRes->m_pNpcSpawn )
	{
		return m_pCMapRes->m_pNpcSpawn->GetNpcInfo( sNpcID );
	}
	return NULL;
}

//
void SubMap::Add(Entity* pCEnt)
{
	DBG_ASSERT_ENTITY(pCEnt);
	CCharacter	*pCCha = pCEnt->IsCharacter();
	CItem		*pCItem;
	Corsairs::Util::Point		l_pt = pCEnt->GetPos();
	Corsairs::Util::Rect		l_rect = GetEyeshot(l_pt);

	if (pCEnt->m_pCEyeshotHost)
	{
		//LG("", " %s [%d, %d] %s [%d, %d]\n", GetName(), l_pt.x, l_pt.y, pCEnt->GetLogName(), pCEnt->m_pCEyeshotHost->m_sPosX, pCEnt->m_pCEyeshotHost->m_sPosY);
		ToLogService("errors", LogLevel::Error, "(switch) map {} to eyeshot cell [{}, {}]add entity {} find it is not break away foregone manage cell[{}, {}]", GetName(), l_pt.X, l_pt.Y, pCEnt->GetLogName(), pCEnt->m_pCEyeshotHost->m_sPosX, pCEnt->m_pCEyeshotHost->m_sPosY);
		return;
	}
	pCEnt->m_pCEyeshotHost = &m_pCEyeshotCell[l_pt.Y][l_pt.X];

	if (pCCha)
	{
		if (pCCha->IsPlayerCha())
		{
			pCCha->GetPlayer()->RefreshMapMask(GetName(), pCCha->GetPos().X / 100, pCCha->GetPos().Y / 100);
			pCCha->Cmd_SetInGymkhana(CanPK());
			pCCha->Cmd_SetPKGuild(GetMapRes()->GetType() == 3);
		}

		if (pCCha->IsPlayerOwnCha())
		{
			m_lPlayerNum++;
//			m_lActivePlayerNum++;
		}
	}

	if (pCCha)
	{
		m_pCEyeshotCell[l_pt.Y][l_pt.X].AddEntity(pCCha);

		std::int32_t l_radius = pCEnt->GetRadius();
		l_pt = pCEnt->GetPos();
		Corsairs::Util::Rect l_range = GetHoldStateCell(l_pt, l_radius);
		for (long i = l_range.LeftTop.Y; i <= l_range.RightBottom.Y; i++)
			for (long j = l_range.LeftTop.X; j <= l_range.RightBottom.X; j++)
			{
				if (i != l_pt.Y || j != l_pt.X)
				{
					//StateCellAddCha(j, i, pCCha, false);
				}
				else {
					StateCellAddCha(j, i, pCCha, true);
				}
			}
	}
	else if (pCItem = pCEnt->IsItem())
	{
		m_pCEyeshotCell[l_pt.Y][l_pt.X].AddEntity(pCItem);
	}

	if( pCCha)
	{
		pCCha->EntryMapUnit( GetMapID(), WORD(l_pt.X), WORD(l_pt.Y) );
	}
}

void SubMap::Delete(Entity* pCEnt)
{
	// pCEnt здесь иногда уже отвязан от карты (asymm с Add), но указатель
	// должен всё ещё указывать на живой пул-объект. Исключение —
	// shutdown / Free, где мы намеренно идём по edges_after_release.
	DBG_ASSERT_ENTITY(pCEnt);
	CCharacter	*pCCha = pCEnt->IsCharacter();
	Corsairs::Util::Point		l_pt = pCEnt->GetPos();
	//const Corsairs::Util::Rect	&m_area = GetRange();
	//if (l_pt.x < m_area.ltop.x || l_pt.x >= m_area.rbtm.x || l_pt.y < m_area.ltop.y || l_pt.y >= m_area.rbtm.y)
	//{
	//	LG("", " %s  %s [%d, %d]\n", GetName(), pCEnt->GetLogName(), l_pt.x, l_pt.y);
	//	return;
	//}
	Corsairs::Util::Rect		l_rect = GetEyeshot(l_pt);

	if (!pCEnt->m_pCEyeshotHost)
	{
		//LG("", " %s [%d, %d] %s \n", GetName(), l_pt.x, l_pt.y, pCEnt->GetLogName());
		ToLogService("errors", LogLevel::Error, "(switch)map {} from eyeshot[{}, {}] delete entity {} find it isn't in eyeshot cell.", GetName(), l_pt.X, l_pt.Y, pCEnt->GetLogName());
		return;
	}
	if (pCEnt->m_pCEyeshotHost != &m_pCEyeshotCell[l_pt.Y][l_pt.X])
	{
		//LG("", " %s [%d, %d] %s [%d, %d]\n", GetName(), l_pt.x, l_pt.y, pCEnt->GetLogName(), pCEnt->m_pCEyeshotHost->m_sPosX, pCEnt->m_pCEyeshotHost->m_sPosY);
		ToLogService("errors", LogLevel::Error, "(switch)map {} from eyeshot[{}, {}]delete entity {}find it isn't agree with log eyeshot cell[{}, {}].", GetName(), l_pt.X, l_pt.Y, pCEnt->GetLogName(), pCEnt->m_pCEyeshotHost->m_sPosX, pCEnt->m_pCEyeshotHost->m_sPosY);
		return;
	}
	pCEnt->m_pCEyeshotHost = 0;

	if (pCCha)
	{
		pCCha->Cmd_SetInGymkhana(false);
		pCCha->Cmd_SetPKGuild(false);

		if (pCCha->IsPlayerOwnCha())
		{
			m_lPlayerNum--;
			//if(pCCha->IsLiveing())
			//	m_lActivePlayerNum--;
		}
	}

	m_pCEyeshotCell[l_pt.Y][l_pt.X].DelEntity(pCEnt);
	CStateCellNode	*pCNode = pCEnt->m_pCStateCellHead;
	if (pCCha)
	{
		while (pCNode)
		{
			StateCellDelCha(pCNode->m_pCStateCell->m_sPosX, pCNode->m_pCStateCell->m_sPosY, pCNode->m_pCChaNode);
			pCNode = pCNode->m_pCNext;
		}
	}
}

// 
void SubMap::MoveInStateCell(CCharacter* pCCha, const Corsairs::Util::Point &SSrcPos, const Corsairs::Util::Point &STarPos)
{
	Corsairs::Util::Point	l_src = SSrcPos;
	Corsairs::Util::Point	l_dst = STarPos;
	std::int32_t	lRadius = pCCha->GetRadius();
	const Corsairs::Util::Rect l_srcTerr = GetHoldStateCell(l_src, lRadius);
	const Corsairs::Util::Rect l_dstTerr = GetHoldStateCell(l_dst, lRadius);

	if (l_src == l_dst)
		return;

	std::int32_t		x, y;
	// 
	CStateCellNode	*pCNode = pCCha->m_pCStateCellHead;
	if (pCCha)
	{
		while (pCNode)
		{
			StateCellDelCha(pCNode->m_pCStateCell->m_sPosX, pCNode->m_pCStateCell->m_sPosY, pCNode->m_pCChaNode);
			pCNode = pCNode->m_pCNext;
		}
	}
	// 
	for (y = l_dstTerr.LeftTop.Y; y <= l_dstTerr.RightBottom.Y; y++)
	{
		for (x = l_dstTerr.LeftTop.X; x <= l_dstTerr.RightBottom.X; x++)
		{
			if (y != l_dst.Y || x != l_dst.X)
			{
				//StateCellAddCha(x, y, pCCha, false); // 
			}
			else
				StateCellAddCha(x, y, pCCha, true); // 
		}
	}
}

void SubMap::MoveInMapMask(CCharacter* pCCha, const Corsairs::Util::Point &SSrcPos, const Corsairs::Util::Point &STarPos)
{
	if (!pCCha->IsPlayerCha())
		return;
	Corsairs::Util::Point	l_src, l_dst;

	long	lStep = 4 * 100;
	l_src.X = SSrcPos.X / lStep;
	l_src.Y = SSrcPos.Y / lStep;
	l_dst.X = STarPos.X / lStep;
	l_dst.Y = STarPos.Y / lStep;
	if (l_src != l_dst)
		pCCha->GetPlayer()->RefreshMapMask(GetName(), STarPos.X / 100, STarPos.Y / 100);
}

//void SubMap::Move(Entity* pCEnt, Corsairs::Util::Point STarPos, char chStep)
//{
//	Corsairs::Util::Point	l_src = pCEnt->GetPos();
//	Corsairs::Util::Point	l_dst = STarPos;
//	std::int32_t	lRadius = pCEnt->GetRadius();
//	const Corsairs::Util::Rect l_srcTerr = GetTerritory(l_src, lRadius);
//	const Corsairs::Util::Rect l_dstTerr = GetTerritory(l_dst, lRadius);
//
//	std::int32_t		x, y;
//	if (chStep == 1) // 
//	{
//		//// log
//		//if (!strcmp("tty", pCEnt->GetName()))
//		//{
//		//	char	szPrint[512] = "";
//		//	LG("", "  [%d,%d]--[%d,%d][%d,%d].\n",
//		//		l_srcTerr.ltop.x, l_srcTerr.ltop.y, l_srcTerr.rbtm.x, l_srcTerr.rbtm.y, l_src.x, l_src.y);
//		//	LG("", "[%d,%d]--[%d,%d][%d,%d].\n",
//		//		l_dstTerr.ltop.x, l_dstTerr.ltop.y, l_dstTerr.rbtm.x, l_dstTerr.rbtm.y, l_dst.x, l_dst.y);
//
//		//	CMgrNode	*pCNode = pCEnt->m_pCMgrNodeHead;
//		//	while (pCNode)
//		//	{
//		//		pCNode = pCNode->m_pCNext;
//		//	}
//		//	LG("", "%s.\n", szPrint);
//		//}
//		////
//
//		CMgrNode	*pCNode = pCEnt->m_pCMgrNodeHead, *pCTempNode;
//		if (pCNode) // 
//		{
//			pCTempNode = pCNode->m_pCNext;
//
//			x = pCNode->m_pCMgrUnit->m_sPosX;
//			y = pCNode->m_pCMgrUnit->m_sPosY;
//			if (x < l_dstTerr.ltop.x || x > l_dstTerr.rbtm.x
//				|| y < l_dstTerr.ltop.y || y > l_dstTerr.rbtm.y) // 
//				pCNode->m_pCMgrUnit->DelEntity(pCNode->m_pCEntityNode);
//			else
//			{
//				if (l_src != l_dst) // 
//					m_pCMgrUnit[y][x]->SetEntityIn(pCNode->m_pCEntityNode, false);
//			}
//
//			pCNode = pCTempNode;
//		}
//		while (pCNode)
//		{
//			pCTempNode = pCNode->m_pCNext;
//
//			x = pCNode->m_pCMgrUnit->m_sPosX;
//			y = pCNode->m_pCMgrUnit->m_sPosY;
//			if (x < l_dstTerr.ltop.x || x > l_dstTerr.rbtm.x
//				|| y < l_dstTerr.ltop.y || y > l_dstTerr.rbtm.y) // 
//				pCNode->m_pCMgrUnit->DelEntity(pCNode->m_pCEntityNode);
//			else
//			{
//				if (l_src != l_dst)
//				{
//					if (l_dst.x == x && l_dst.y == y) // 
//						m_pCMgrUnit[y][x]->SetEntityIn(pCNode->m_pCEntityNode);
//				}
//			}
//
//			pCNode = pCTempNode;
//		}
//
//		//// log
//		//if (!strcmp("tty", pCEnt->GetName()))
//		//{
//		//	char	szPrint[512] = "";
//		//	CMgrNode	*pCNode = pCEnt->m_pCMgrNodeHead;
//		//	while (pCNode)
//		//	{
//		//		pCNode = pCNode->m_pCNext;
//		//	}
//		//	LG("", "%s.\n", szPrint);
//
//		//	LG("", "\n");
//		//	for (y = l_srcTerr.ltop.y; y <= l_srcTerr.rbtm.y; y++)
//		//		for (x = l_srcTerr.ltop.x; x <= l_srcTerr.rbtm.x; x++)
//		//		{
//		//			szPrint[0] = '\0';
//		//			CEntityListNode	*pCNode = m_pCMgrUnit[y][x]->m_pCChaIn;
//		//			while (pCNode)
//		//			{
//		//				pCNode = pCNode->m_pCNext;
//		//			}
//		//			LG("", "\t[%d,%d]%s\n", x, y, szPrint);
//		//			szPrint[0] = '\0';
//		//			pCNode = m_pCMgrUnit[y][x]->m_pCChaCross;
//		//			while (pCNode)
//		//			{
//		//				pCNode = pCNode->m_pCNext;
//		//			}
//		//			LG("", "\t[%d,%d]%s\n", x, y, szPrint);
//		//		}
//		//}
//		////
//	}
//	else if (chStep == 2) // 
//	{
//		pCEnt->SetPos(STarPos);
//		if (l_src != l_dst)
//			pCEnt->RefreshArea();
//		for (y = l_dstTerr.ltop.y; y <= l_dstTerr.rbtm.y; y++)
//		{
//			for (x = l_dstTerr.ltop.x; x <= l_dstTerr.rbtm.x; x++)
//			{
//				if (x < l_srcTerr.ltop.x || x > l_srcTerr.rbtm.x
//					|| y < l_srcTerr.ltop.y || y > l_srcTerr.rbtm.y) // 
//				{
//					if (y != l_dst.y || x != l_dst.x)
//						MgrUnitAddEntity(x, y, pCEnt, def_MGRUNIT_ENTITY_TYPE_CHACROSS); // 
//					else
//						MgrUnitAddEntity(x, y, pCEnt, def_MGRUNIT_ENTITY_TYPE_CHAIN); // 
//				}
//			}
//		}
//
//		//// log
//		//if (!strcmp("tty", pCEnt->GetName()))
//		//{
//		//	char	szPrint[512] = "";
//
//		//	CMgrNode	*pCNode = pCEnt->m_pCMgrNodeHead;
//		//	while (pCNode)
//		//	{
//		//		pCNode = pCNode->m_pCNext;
//		//	}
//		//	LG("", "%s.\n", szPrint);
//
//		//	LG("", "\n");
//		//	for (y = l_dstTerr.ltop.y; y <= l_dstTerr.rbtm.y; y++)
//		//		for (x = l_dstTerr.ltop.x; x <= l_dstTerr.rbtm.x; x++)
//		//		{
//		//			szPrint[0] = '\0';
//		//			CEntityListNode	*pCNode = m_pCMgrUnit[y][x]->m_pCChaIn;
//		//			while (pCNode)
//		//			{
//		//				pCNode = pCNode->m_pCNext;
//		//			}
//		//			LG("", "\t[%d,%d]%s\n", x, y, szPrint);
//		//			szPrint[0] = '\0';
//		//			pCNode = m_pCMgrUnit[y][x]->m_pCChaCross;
//		//			while (pCNode)
//		//			{
//		//				pCNode = pCNode->m_pCNext;
//		//			}
//		//			LG("", "\t[%d,%d]%s\n", x, y, szPrint);
//		//		}
//		//	LG("", "\n");
//		//}
//		////
//	}
//}
//
//=============================================================================
// 
// bActiveMgr 
//=============================================================================
bool SubMap::Enter(Corsairs::Util::Square* pSEntShape, Entity * ent, const int32_t clSearchRadius)
{
	ent->SetInitShape(*pSEntShape);

	const	Corsairs::Util::Point l_pt = pSEntShape->Centre;
	bool	l_retval = true;
	Corsairs::Util::Point	l_pt2, l_pt1;

	l_pt1 = l_pt;
	Corsairs::Util::Rect	l_rect = GetEyeshot(l_pt1);
	long	lStep = pSEntShape->Radius;

	if (lStep == 0) // 0
		lStep = 40;

	//
	ent->m_submap	=this;
	long l_xdlt	=0,l_ydlt	=0;
	
	if (clSearchRadius > 0)
	{
		if(ent->overlap(l_xdlt,l_ydlt))
		{
			long l_dist =0;
			bool l_overflag =true;
			while(l_overflag) //
			{
				l_dist++;
				for(short dir=0;dir<4;dir++){
					l_pt1	=l_pt;
					//long l_radius	=2 * lStep * l_dist;
					long l_radius	=GetBlockCellWidth() * l_dist;
					if(l_radius >clSearchRadius){
						l_retval	=false;
						l_overflag	=false;
						break;
					}
					l_pt1.Move(dir*90,l_radius);
					l_pt2	=l_pt1;
					l_rect =GetEyeshot(l_pt2);

					ent->SetPos(l_pt1);
					l_xdlt	=l_ydlt		=0;

					if(!(l_overflag =ent->overlap(l_xdlt,l_ydlt))){
						l_retval	=true;
						break;
					}
				}
			}
		}
	}
	else if (clSearchRadius == 0)
	{
		if(ent->overlap(l_xdlt,l_ydlt))
			l_retval = false;
	}
	else // 
	{}
	//beginsee
	if(l_retval)
	{
		bool	bActive = ent->GetEyeshotAbility();

		for(long y =l_rect.LeftTop.Y;y <=l_rect.RightBottom.Y;y++)
		{
			for(long x =l_rect.LeftTop.X;x <=l_rect.RightBottom.X;x++)
			{
				if (bActive)
					ActiveEyeshotCell(x, y);

				m_pCEyeshotCell[y][x].EnterEyeshot(ent);
			}
		}

		//
		ent->RefreshArea();
		Add(ent);		
		ent->m_lastpos	=ent->GetPos();
	}
	else
		ent->m_submap = 0;


	return l_retval;
}

// Enter
bool SubMap::EnsurePos(Corsairs::Util::Square* pSEntShape, Entity * ent, const int32_t clSearchRadius)
{
	ent->SetInitShape(*pSEntShape);

	const	Corsairs::Util::Point l_pt = pSEntShape->Centre;
	bool	l_retval = true;
	Corsairs::Util::Point	l_pt2, l_pt1;

	l_pt1 = l_pt;
	long	lStep = pSEntShape->Radius;

	if (lStep == 0) // 0
		lStep = 40;

	//
	ent->m_submap	=this;
	long l_xdlt	=0,l_ydlt	=0;
	
	if (clSearchRadius > 0)
	{
		if(ent->overlap(l_xdlt,l_ydlt))
		{
			long l_dist =0;
			bool l_overflag =true;
			while(l_overflag) //
			{
				l_dist++;
				for(short dir=0;dir<6;dir++){
					l_pt1	=l_pt;
					long l_radius	=2 * lStep * l_dist;
					if(l_radius >clSearchRadius){
						l_retval	=false;
						l_overflag	=false;
						break;
					}
					l_pt1.Move(dir*60,l_radius);
					l_pt2	=l_pt1;

					ent->SetPos(l_pt1);
					l_xdlt	=l_ydlt		=0;

					if(!(l_overflag =ent->overlap(l_xdlt,l_ydlt))){
						l_retval	=true;
						break;
					}
				}
			}
		}
	}
	else if (clSearchRadius == 0)
	{
		if(ent->overlap(l_xdlt,l_ydlt))
			l_retval = false;
	}
	else // 
	{}
	//beginsee
	if(!l_retval)
		ent->m_submap = 0;


	return l_retval;
}

//=============================================================================
// 
// bActiveMgr 
//=============================================================================
void SubMap::GoOut(Entity * ent)
{
	DBG_ASSERT_ENTITY(ent);
#if defined(_DEBUG)
	const void* l_dbgEnt = static_cast<const void*>(ent);
	const char* l_dbgName = ent->GetLogName();
#endif
	Corsairs::Util::Point l_pt =ent->GetShape().Centre;
	Corsairs::Util::Rect l_rect =GetEyeshot(l_pt);
	//
	Delete(ent);
	//endsee

	bool	bActive = ent->GetEyeshotAbility();

	for(long y =l_rect.LeftTop.Y;y <=l_rect.RightBottom.Y;y++)
	{
		for(long x =l_rect.LeftTop.X;x <=l_rect.RightBottom.X;x++)
		{
			if (bActive)
				InactiveEyeshotCell(x, y);

			m_pCEyeshotCell[y][x].OutEyeshot(ent);
		}
	}

#if defined(_DEBUG)
	// Форензик-скан: пробегаем ВСЕ клетки карты — ent должен быть
	// нигде (ни в m_pCChaL, ни в m_pCItemL, ни в next/last-связях).
	// Если найден — это root-cause "item остался после pickup":
	// Delete удалил его только из одного cell, а он был ещё где-то.
	const long l_lins = GetEyeshotCellLin();
	const long l_cols = GetEyeshotCellCol();
	for (long cy = 0; cy < l_lins; ++cy)
	{
		for (long cx = 0; cx < l_cols; ++cx)
		{
			CEyeshotCell& l_cell = m_pCEyeshotCell[cy][cx];
			for (const Entity* p = l_cell.m_pCChaL; p; p = p->m_pCEyeshotCellNext)
			{
				if (p == ent)
				{
					ToLogService("errors", LogLevel::Error,
						"SubMap::GoOut LEAK: ent={} name='{}' still in cell[{}][{}].m_pCChaL after Delete+OutEyeshot. "
						"Initial pos=[{},{}] eyeshot-rect=[{},{}..{},{}].",
						l_dbgEnt, l_dbgName, cy, cx, l_pt.X, l_pt.Y,
						l_rect.LeftTop.X, l_rect.LeftTop.Y, l_rect.RightBottom.X, l_rect.RightBottom.Y);
					break;
				}
			}
			for (const Entity* p = l_cell.m_pCItemL; p; p = p->m_pCEyeshotCellNext)
			{
				if (p == ent)
				{
					ToLogService("errors", LogLevel::Error,
						"SubMap::GoOut LEAK: ent={} name='{}' still in cell[{}][{}].m_pCItemL after Delete+OutEyeshot. "
						"Initial pos=[{},{}] eyeshot-rect=[{},{}..{},{}].",
						l_dbgEnt, l_dbgName, cy, cx, l_pt.X, l_pt.Y,
						l_rect.LeftTop.X, l_rect.LeftTop.Y, l_rect.RightBottom.X, l_rect.RightBottom.Y);
					break;
				}
			}
		}
	}
#endif

	ent->m_submap =0;
}

// 
void SubMap::RefreshEyeshot(Entity *pCEnt, bool bEyeshot, bool bHide, bool bShow)
{
	Corsairs::Util::Point l_pt = pCEnt->GetShape().Centre;
	Corsairs::Util::Rect l_rect = GetEyeshot(l_pt);

	for(long y =l_rect.LeftTop.Y;y <=l_rect.RightBottom.Y;y++)
	{
		for(long x =l_rect.LeftTop.X;x <=l_rect.RightBottom.X;x++)
		{
			m_pCEyeshotCell[y][x].RefreshEyeshot(pCEnt, bEyeshot, bHide, bShow);
		}
	}
}

Corsairs::Util::Rect SubMap::GetEyeshot(Corsairs::Util::Point &pt)const
{
	const Corsairs::Util::Rect	&m_area = GetRange();
	Corsairs::Util::Rect l_rect;
	pt.X	=(pt.X - m_area.LeftTop.X)/GetEyeshotCellWidth();
	pt.Y	=(pt.Y - m_area.LeftTop.Y)/GetEyeshotCellHeight();
	l_rect.LeftTop.X	=max(pt.X -GetEyeshotWidth(),0);
	l_rect.LeftTop.Y	=max(pt.Y -GetEyeshotWidth(),0);
	l_rect.RightBottom.X	=min(pt.X +GetEyeshotWidth(),GetEyeshotCellCol() -1);
	l_rect.RightBottom.Y	=min(pt.Y +GetEyeshotWidth(),GetEyeshotCellLin() -1);
	return l_rect;
}

Corsairs::Util::Rect SubMap::GetEyeshot(short sMgrUnitX, short sMgrUnitY)const
{
	Corsairs::Util::Rect	l_rect;

	l_rect.LeftTop.X = max(sMgrUnitX - GetEyeshotWidth(), 0);
	l_rect.LeftTop.Y = max(sMgrUnitY - GetEyeshotWidth(), 0);
	l_rect.RightBottom.X = min(sMgrUnitX + GetEyeshotWidth(), GetEyeshotCellCol() -1);
	l_rect.RightBottom.Y = min(sMgrUnitY + GetEyeshotWidth(), GetEyeshotCellLin() -1);

	return l_rect;
}

void SubMap::GetEyeshotCenter(Corsairs::Util::Point &pt)
{
	const Corsairs::Util::Rect	&m_area = GetRange();
	pt.X	=(pt.X - m_area.LeftTop.X) / GetEyeshotCellWidth();
	pt.Y	=(pt.Y - m_area.LeftTop.Y) / GetEyeshotCellHeight();
}

Corsairs::Util::Rect SubMap::GetHoldStateCell(Corsairs::Util::Point &pt, std::int32_t lRadius) const 
{
	const Corsairs::Util::Rect	&m_area = GetRange();
	Corsairs::Util::Rect l_rect;
	if (lRadius > 0)
	{
		l_rect.LeftTop.X = (pt.X - lRadius - m_area.LeftTop.X) / GetStateCellWidth();
		l_rect.LeftTop.Y = (pt.Y - lRadius - m_area.LeftTop.Y) / GetStateCellHeight();
		l_rect.RightBottom.X = (pt.X + lRadius - m_area.LeftTop.X) / GetStateCellWidth();
		l_rect.RightBottom.Y = (pt.Y + lRadius - m_area.LeftTop.X) / GetStateCellHeight();

		if (l_rect.LeftTop.X < 0) l_rect.LeftTop.X = 0;
		if (l_rect.RightBottom.X >= GetStateCellCol()) l_rect.RightBottom.X = GetStateCellCol() -1;
		if (l_rect.LeftTop.Y < 0) l_rect.LeftTop.Y = 0;
		if (l_rect.RightBottom.Y >= GetStateCellLin()) l_rect.RightBottom.Y = GetStateCellLin() -1;
	}
	else
	{
		l_rect.LeftTop.X = pt.X / GetStateCellWidth();
		l_rect.LeftTop.Y = pt.Y / GetStateCellHeight();
		l_rect.RightBottom.X = pt.X / GetStateCellWidth();
		l_rect.RightBottom.Y = pt.Y / GetStateCellHeight();
	}
	pt.X = (pt.X - m_area.LeftTop.X) / GetStateCellWidth();
	pt.Y = (pt.Y - m_area.LeftTop.Y) / GetStateCellHeight();

	return l_rect;
}

void SubMap::GetHoldStateCellCenter(Corsairs::Util::Point &pt)
{
	const Corsairs::Util::Rect	&m_area = GetRange();
	pt.X = (pt.X - m_area.LeftTop.X) / GetStateCellWidth();
	pt.Y = (pt.Y - m_area.LeftTop.Y) / GetStateCellHeight();
}

//===============Search===================================================================================
CCharacter*	SubMap::FindCharacter( std::uint32_t ulID, const Corsairs::Util::Point& point )
{
	CCharacter* pCha = NULL;
	std::int32_t	lRangeB[] = {point.X, point.Y, 0};
	std::int32_t	lRangeE[] = {enumRANGE_TYPE_CIRCLE, 10 * 100};
	BeginSearchInRange(lRangeB, lRangeE);
	while (pCha = GetNextCharacterInRange())
	{
		if(pCha->GetID() == ulID)
			break;
	}

	return pCha;
}

//=============================================================================
// plRangeBParam  defSKILL_RANGE_BASEP_NUM  
// plRangeEParam  defSKILL_RANGE_EXTEP_NUM  
// bIncludeHideEnti 
//=============================================================================
void SubMap::BeginSearchInRange(std::int32_t *plRangeBParam, std::int32_t *plRangeEParam, bool bIncludeHideEnti)
{
    m_sRangeCurMgrUnit = -1;
	m_pRangeCurEntiNode = 0;
	m_bIncludeHideEnti = bIncludeHideEnti;

	std::int32_t	lCx = plRangeBParam[0];
	std::int32_t	lCy = plRangeBParam[1];
	std::int32_t	lAngle = plRangeBParam[2];
	std::int32_t	lRangeType = plRangeEParam[0];

	std::int32_t	lUnitSX, lUnitEX, lUnitSY, lUnitEY;
	std::int32_t	lMaxRadius;
	if (lRangeType == enumRANGE_TYPE_STICK)
	{
		std::int32_t	lRadius = plRangeEParam[1];
		std::int32_t	lWidth = plRangeEParam[2];

		m_pCBaseRange = &m_CStickRange;
		m_CStickRange.setPos(lCx, lCy);
		m_CStickRange.setAngle(lAngle);
		m_CStickRange.setRadius(lRadius);
		m_CStickRange.setWidth(lWidth);

		lMaxRadius = (std::int32_t)sqrt(double(lRadius * lRadius + (lWidth / 2) * (lWidth / 2)));
	}
	else if (lRangeType == enumRANGE_TYPE_FAN)
	{
		std::int32_t	lRadius = plRangeEParam[1];
		std::int32_t	lAngleD = plRangeEParam[2];

		m_pCBaseRange = &m_CFanRange;
		m_CFanRange.setPos(lCx, lCy);
		lAngle = lAngle - lAngleD / 2;
		if (lAngle < 0)
			lAngle += 360;
		m_CFanRange.setAngle(lAngle);
		m_CFanRange.setAngleStep(lAngleD);
		m_CFanRange.setRadius(lRadius);

		lMaxRadius = lRadius;
	}
	else if (lRangeType == enumRANGE_TYPE_SQUARE)
	{
		std::int32_t	lRadius = plRangeEParam[1];

		m_pCBaseRange = &m_CSquareCRange;
		m_CSquareCRange.setPos(lCx, lCy);
		m_CSquareCRange.setAngle(lAngle);
		m_CSquareCRange.setRadius(lRadius);

		lMaxRadius = lRadius;
	}
	else if (lRangeType == enumRANGE_TYPE_CIRCLE)
	{
		std::int32_t	lRadius = plRangeEParam[1];

		m_pCBaseRange = &m_CCircleRange;
		m_CCircleRange.setPos(lCx, lCy);
		m_CCircleRange.setRadius(lRadius);

		lMaxRadius = lRadius;
	}
	else
		m_pCBaseRange = 0;

	if (!m_pCBaseRange)
		return;

	m_lRangeCentUnit[0] = lCx / GetStateCellWidth();
	m_lRangeCentUnit[1] = lCy / GetStateCellHeight();

	lUnitSX = (lCx - lMaxRadius) / GetStateCellWidth();
	lUnitEX = (lCx + lMaxRadius) / GetStateCellWidth();
	lUnitSY = (lCy - lMaxRadius) / GetStateCellHeight();
	lUnitEY = (lCy + lMaxRadius) / GetStateCellHeight();
	lUnitSX = lUnitSX < 0 ? 0 : lUnitSX;
	lUnitEX = lUnitEX > GetStateCellCol() -1 ? GetStateCellCol() -1 : lUnitEX;
	lUnitSY = lUnitSY < 0 ? 0 : lUnitSY;
	lUnitEY = lUnitEY > GetStateCellLin() -1 ? GetStateCellLin() -1 : lUnitEY;

	m_sRangeMgrUnitNum = 0;
	std::int32_t	sx, sy, ex, ey;
	for (int i = lUnitSY; i <= lUnitEY; i++)
		for (int j = lUnitSX; j <= lUnitEX; j++)
		{
			sx = j * GetStateCellWidth();
			ex = sx + GetStateCellWidth() - 1;
			sy = i * GetStateCellHeight();
			ey = sy + GetStateCellHeight() - 1;
			if (m_pCBaseRange->RectHitTest(sx, sy, ex, ey)) // 
			{
				m_lRangeMgrUnit[m_sRangeMgrUnitNum][0] = j;
				m_lRangeMgrUnit[m_sRangeMgrUnitNum][1] = i;
				m_sRangeMgrUnitNum++;
				if (m_sRangeMgrUnitNum >= defRANGE_MGRUNIU_NUM)
				{
					//MessageBox(NULL, "", "", MB_OK);
					MessageBox(NULL, RES_STRING(GM_SUBMAP_CPP_00004), RES_STRING(GM_SUBMAP_CPP_00005), MB_OK);
					return;
				}
			}
		}
}

CCharacter* SubMap::GetNextCharacterInRange(void)
{
	if (!m_pCBaseRange)
		return 0;

Research:
	if (m_pRangeCurEntiNode)
		m_pRangeCurEntiNode = m_pRangeCurEntiNode->m_pCNext;

	while (!m_pRangeCurEntiNode)
	{
		m_sRangeCurMgrUnit++;
		if (m_sRangeCurMgrUnit >= m_sRangeMgrUnitNum)
			return 0;
		if (auto* cell = _stateCellGrid.Get(static_cast<short>(m_lRangeMgrUnit[m_sRangeCurMgrUnit][0]),
										   static_cast<short>(m_lRangeMgrUnit[m_sRangeCurMgrUnit][1]))) {
			m_pRangeCurEntiNode = cell->m_pCChaIn;
		}
	}

	if (m_pRangeCurEntiNode)
	{
		if (!m_bIncludeHideEnti)
		{
			CCharacter	*pCCha = m_pRangeCurEntiNode->m_pCCha;
			if (pCCha && pCCha->IsHide())
				goto Research;
			else
				return pCCha;
		}
		else
			return m_pRangeCurEntiNode->m_pCCha;
	}
	else
		return 0;
}

//=============================================================================
// BeginSearchInRange
//=============================================================================
bool SubMap::RangeAddState(std::uint8_t uchFightID, std::uint32_t ulSrcWorldID, std::int32_t lSrcHandle,
						   char chObjType, char chObjHabitat, char chEffType, int16_t *sStateParam)
{
	if (sStateParam[0] > AREA_STATE_MAXID || sStateParam[1] > SKILL_STATE_LEVEL)
		return false;

	if (!m_pCBaseRange)
		return false;

	CSkillStateRecord	*pSStateR = 0;
	pSStateR = GetCSkillStateRecordInfo(sStateParam[0]);
	if (!pSStateR)
		return false;

	std::int32_t	x, y;
	std::uint32_t	ulStartTick = GetTickCount();
	bool	bAddSuc;
	bool	bAlreadyHas;
	for (int16_t i = 0; i < m_sRangeMgrUnitNum; i++)
	{
		bAddSuc = false;
		bAlreadyHas = false;
		x = m_lRangeMgrUnit[i][0], y = m_lRangeMgrUnit[i][1];

		{
			auto* cell = _stateCellGrid.Get(static_cast<short>(x), static_cast<short>(y));
			if (cell && cell->m_CSkillState.HasState((std::uint8_t)sStateParam[0])) {
				bAlreadyHas = true;
			}
		}
		if (x == m_lRangeCentUnit[0] && y == m_lRangeCentUnit[1])
			bAddSuc = AddCellState(uchFightID, ulSrcWorldID, lSrcHandle, chObjType, chObjHabitat, chEffType, x, y, (std::uint8_t)sStateParam[0], (std::uint8_t)sStateParam[1], ulStartTick, sStateParam[2], pSStateR->chAddType, 1);
		else
			bAddSuc = AddCellState(uchFightID, ulSrcWorldID, lSrcHandle, chObjType, chObjHabitat, chEffType, x, y, (std::uint8_t)sStateParam[0], (std::uint8_t)sStateParam[1], ulStartTick, sStateParam[2], pSStateR->chAddType, 0);
		if (!bAlreadyHas && bAddSuc)
		{
			NotiStateCellToEyeshot((short)x, (short)y);
		}
	}

	return true;
}

bool SubMap::RangeAddState(Corsairs::Util::Rect *pSRange, std::uint8_t uchFightID, std::uint32_t ulSrcWorldID, std::int32_t lSrcHandle,
						   char chObjType, char chObjHabitat, char chEffType, int16_t *sStateParam)
{
	if (sStateParam[0] > AREA_STATE_MAXID || sStateParam[1] > SKILL_STATE_LEVEL)
		return false;

	CSkillStateRecord	*pSStateR = 0;
	pSStateR = GetCSkillStateRecordInfo(sStateParam[0]);
	if (!pSStateR)
		return false;

	std::int32_t	lUnitSX, lUnitEX, lUnitSY, lUnitEY, lUnitCX, lUnitCY;
	lUnitSX = pSRange->LeftTop.X / GetStateCellWidth();
	lUnitEX = pSRange->RightBottom.X / GetStateCellWidth();
	lUnitSY = pSRange->LeftTop.Y / GetStateCellHeight();
	lUnitEY = pSRange->RightBottom.Y / GetStateCellHeight();
	lUnitSX = lUnitSX < 0 ? 0 : lUnitSX;
	lUnitEX = lUnitEX > GetStateCellCol() -1 ? GetStateCellCol() -1 : lUnitEX;
	lUnitSY = lUnitSY < 0 ? 0 : lUnitSY;
	lUnitEY = lUnitEY > GetStateCellLin() -1 ? GetStateCellLin() -1 : lUnitEY;

	lUnitCX = lUnitSX + (lUnitEX - lUnitSX) / 2;
	lUnitCY = lUnitSY + (lUnitEY - lUnitSY) / 2;

	std::uint32_t	ulStartTick = GetTickCount();
	bool	bAddSuc;
	bool	bAlreadyHas;
	for (std::int32_t y = lUnitSY; y <= lUnitEY; y++)
		for (std::int32_t x = lUnitSX; x <= lUnitEX; x++)
		{
			bAddSuc = false;
			bAlreadyHas = false;

			{
				auto* cell = _stateCellGrid.Get(static_cast<short>(x), static_cast<short>(y));
				if (cell && cell->m_CSkillState.HasState((std::uint8_t)sStateParam[0])) {
					bAlreadyHas = true;
				}
			}
			if (y == lUnitCY && x == lUnitCX)
				bAddSuc = AddCellState(uchFightID, ulSrcWorldID, lSrcHandle, chObjType, chObjHabitat, chEffType, x, y, (std::uint8_t)sStateParam[0], (std::uint8_t)sStateParam[1], ulStartTick, sStateParam[2], pSStateR->chAddType, 1);
			else
				bAddSuc = AddCellState(uchFightID, ulSrcWorldID, lSrcHandle, chObjType, chObjHabitat, chEffType, x, y, (std::uint8_t)sStateParam[0], (std::uint8_t)sStateParam[1], ulStartTick, sStateParam[2], pSStateR->chAddType, 0);
			if (!bAlreadyHas && bAddSuc)
			{
				auto* cell = _stateCellGrid.Get(static_cast<short>(x), static_cast<short>(y));
				ActiveEyeshotCell(cell->m_pCEyeshotCell->m_sPosX, cell->m_pCEyeshotCell->m_sPosY);
				NotiStateCellToEyeshot((short)x, (short)y);
			}
		}

	return true;
}

void SubMap::NotiStateCellToEyeshot(int16_t sCellX, int16_t sCellY)
{
	auto* cell = _stateCellGrid.Get(sCellX, sCellY);
	if (!cell) {
		return;
	}

	auto pk = Corsairs::Net::Msg::serialize(Corsairs::Net::Msg::McAStateBeginSeeMessage{
		static_cast<int64_t>(sCellX), static_cast<int64_t>(sCellY),
		cell->m_CSkillState.BuildStateEntries()
	});

	Corsairs::Util::Rect	l_rect = GetEyeshot(cell->m_pCEyeshotCell->m_sPosX, cell->m_pCEyeshotCell->m_sPosY);
	Entity		*pCEnt;
	CCharacter	*pCCha;
	std::vector<CPlayer*> recipients;
	for (long y = l_rect.LeftTop.Y; y <= l_rect.RightBottom.Y; y++)
	{
		for (long x = l_rect.LeftTop.X; x <= l_rect.RightBottom.X; x++)
		{
			pCEnt = m_pCEyeshotCell[y][x].m_pCChaL;
			while (pCEnt)
			{
				pCCha = pCEnt->IsCharacter();
				if(pCCha->IsPlayerFocusCha())
				{
					recipients.push_back(pCCha->GetPlayer());
				}
				pCEnt = pCEnt->m_pCEyeshotCellNext;
			}
		}
	}
	SENDTOCLIENT(pk, recipients);
}

//=============================================================================
// 
//=============================================================================
void SubMap::MoveTo(Entity *pCEnt, const Corsairs::Util::Point &STar)
{
	if (pCEnt->GetPos() != pCEnt->m_lastpos)
	{
		char	szMess[512];
		{
			auto _s = std::format("character {} move originality coordinate errorlast time position[{}, {}]current position[{}, {}]aim position[{}, {}]",
				pCEnt->GetLogName(), pCEnt->m_lastpos.X, pCEnt->m_lastpos.Y, pCEnt->GetPos().X, pCEnt->GetPos().Y, STar.X, STar.Y);
			std::strncpy(szMess, _s.c_str(), sizeof(szMess) - 1);
			szMess[sizeof(szMess) - 1] = 0;
		}
		//::MessageBox(0,szMess,"!",MB_OK);
		//LG("", "%s\n", szMess);
		ToLogService("errors", LogLevel::Error, "{}", szMess);
		pCEnt->SetPos(pCEnt->m_lastpos);
	}
	Corsairs::Util::Point	l_src = pCEnt->GetPos();
	Corsairs::Util::Point	l_dst = STar;
	Corsairs::Util::Point	SrcPos = l_src;
	const Corsairs::Util::Rect l_srcEyeshot = GetEyeshot(l_src);
	const Corsairs::Util::Rect l_dstEyeshot = GetEyeshot(l_dst);

	Corsairs::Util::MPTimer tMoveState, tMoveMMask, tMoveEyeshot, tMoveArea;
	tMoveState.Begin();
	MoveInStateCell(pCEnt->IsCharacter(), pCEnt->GetPos(), STar);
	tMoveState.End();
	tMoveMMask.Begin();
	MoveInMapMask(pCEnt->IsCharacter(), pCEnt->GetPos(), STar);
	tMoveMMask.End();
	tMoveEyeshot.Begin();
	pCEnt->SetPos(STar);
	if (l_src != l_dst) // 
	{
		//
		if (!pCEnt->m_pCEyeshotHost)
		{
			//LG("", " %s [%d, %d] %s \n", GetName(), l_src.x, l_src.y, pCEnt->GetLogName());
			ToLogService("errors", LogLevel::Error, "(move)map  {} from eyeshot cell[{}, {}]delete entity {} find it isn't in the eyeshot cell.", GetName(), l_src.X, l_src.Y, pCEnt->GetLogName());
			return;
		}
		if (pCEnt->m_pCEyeshotHost != &m_pCEyeshotCell[l_src.Y][l_src.X])
		{
			//LG("", " %s [%d, %d] %s [%d, %d]\n", GetName(), l_src.x, l_src.y, pCEnt->GetLogName(), pCEnt->m_pCEyeshotHost->m_sPosX, pCEnt->m_pCEyeshotHost->m_sPosY);
			ToLogService("errors", LogLevel::Error, "(move)map {} from eyeshot cell[{}, {}]delete entity {} ,find it isn't agree with log eyeshot cell[{}, {}].", GetName(), l_src.X, l_src.Y, pCEnt->GetLogName(), pCEnt->m_pCEyeshotHost->m_sPosX, pCEnt->m_pCEyeshotHost->m_sPosY);
			return;
		}
		pCEnt->m_pCEyeshotHost = 0;
		m_pCEyeshotCell[l_src.Y][l_src.X].DelEntity(pCEnt);

		bool	bActive = pCEnt->GetEyeshotAbility();

		////beginsee and endsee
		//long	lXDist, lYDist, lXStep, lYStep, lSrcXStart, lTarXStart, lSrcYStart, lTarYStart;
		//lXDist = abs(l_src.x - l_dst.x);
		//if (lXDist > GetEyeshotWidth() * 2 + 1)
		//	lXDist = GetEyeshotWidth() * 2 + 1;
		//if (lXDist > 0)
		//{
		//	if (l_src.x >= l_dst.x)
		//	{
		//		if (l_srcEyeshot.rbtm.x == GetEyeshotCellCol() - 1)
		//			lSrcXStart = l_src.x + GetEyeshotWidth() - lXDist + 1;
		//		else
		//			lSrcXStart = l_srcEyeshot.rbtm.x - lXDist + 1;
		//		if (l_dstEyeshot.ltop.x == 0)
		//			lTarXStart = l_dst.x - GetEyeshotWidth();
		//		else
		//			lTarXStart = l_dstEyeshot.ltop.x;
		//	}
		//	else
		//	{
		//		if (l_srcEyeshot.ltop.x == 0)
		//			lSrcXStart = l_src.x - GetEyeshotWidth();
		//		else
		//			lSrcXStart = l_srcEyeshot.ltop.x;
		//		if (l_dstEyeshot.rbtm.x == GetEyeshotCellCol() - 1)
		//			lTarXStart = l_dst.x + GetEyeshotWidth() - lXDist + 1;
		//		else
		//			lTarXStart = l_dstEyeshot.rbtm.x - lXDist + 1;
		//	}

		//	for (long x = 0; x < lXDist; x++)
		//	{
		//		lXStep = lSrcXStart + x;
		//		if ((lXStep >= 0) && (lXStep <= GetEyeshotCellCol() - 1))
		//		{
		//			for (long y = l_srcEyeshot.ltop.y; y <= l_srcEyeshot.rbtm.y; y++)
		//			{
		//				if (bActive)
		//					InactiveEyeshotCell(lXStep, y);
		//				m_pCEyeshotCell[y][lXStep].OutEyeshot(pCEnt);
		//			}
		//		}
		//		lXStep = lTarXStart + x;
		//		if ((lXStep >= 0) && (lXStep <= GetEyeshotCellCol() - 1))
		//		{
		//			for (long y = l_dstEyeshot.ltop.y; y <= l_dstEyeshot.rbtm.y; y++)
		//			{
		//				if (bActive)
		//					ActiveEyeshotCell(lXStep, y);
		//				m_pCEyeshotCell[y][lXStep].EnterEyeshot(pCEnt);
		//			}
		//		}
		//	}
		//}

		//lXDist = abs(l_src.x - l_dst.x);
		//lYDist = abs(l_src.y - l_dst.y);
		//if ((lYDist > 0) && (lXDist < GetEyeshotWidth() * 2 + 1))
		//{
		//	lXDist = GetEyeshotWidth() * 2 + 1 - lXDist;
		//	if (l_src.x >= l_dst.x)
		//	{
		//		if (l_srcEyeshot.ltop.x == 0)
		//		{
		//			lSrcXStart = 0;
		//			lXDist += l_src.x - GetEyeshotWidth();
		//		}
		//		else
		//			lSrcXStart = l_srcEyeshot.ltop.x;
		//	}
		//	else
		//	{
		//		if (l_dstEyeshot.ltop.x == 0)
		//		{
		//			lSrcXStart = 0;
		//			lXDist += l_dst.x - GetEyeshotWidth();
		//		}
		//		else
		//			lSrcXStart = l_dstEyeshot.ltop.x;
		//	}
		//	if (lYDist > GetEyeshotWidth() * 2 + 1)
		//		lYDist = GetEyeshotWidth() * 2 + 1;
		//	if (l_src.y >= l_dst.y)
		//	{
		//		if (l_srcEyeshot.rbtm.y == GetEyeshotCellLin() - 1)
		//			lSrcYStart = l_src.y + GetEyeshotWidth() - lYDist + 1;
		//		else
		//			lSrcYStart = l_srcEyeshot.rbtm.y - lYDist + 1;
		//		if (l_dstEyeshot.ltop.y == 0)
		//			lTarYStart = l_dst.y - GetEyeshotWidth();
		//		else
		//			lTarYStart = l_dstEyeshot.ltop.y;
		//	}
		//	else
		//	{
		//		if (l_srcEyeshot.ltop.y == 0)
		//			lSrcYStart = l_src.y - GetEyeshotWidth();
		//		else
		//			lSrcYStart = l_srcEyeshot.ltop.y;
		//		if (l_dstEyeshot.rbtm.y == GetEyeshotCellLin() - 1)
		//			lTarYStart = l_dst.y + GetEyeshotWidth() - lYDist + 1;
		//		else
		//			lTarYStart = l_dstEyeshot.rbtm.y - lYDist + 1;
		//	}
		//	for (long x = 0; x < lXDist; x++)
		//	{
		//		lXStep = lSrcXStart + x;
		//		for (long y = 0; y < lYDist; y++)
		//		{
		//			lYStep = lSrcYStart + y;
		//			if ((lYStep >= 0) && (lYStep <= GetEyeshotCellLin() - 1))
		//			{
		//				if (bActive)
		//					InactiveEyeshotCell(lXStep, lYStep);
		//				m_pCEyeshotCell[lYStep][lXStep].OutEyeshot(pCEnt);
		//			}

		//			lYStep = lTarYStart + y;
		//			if ((lYStep >= 0) && (lYStep <= GetEyeshotCellLin() - 1))
		//			{
		//				if (bActive)
		//					ActiveEyeshotCell(lXStep, lYStep);
		//				m_pCEyeshotCell[lYStep][lXStep].EnterEyeshot(pCEnt);
		//			}
		//		}
		//	}
		//}

		const long l_xmin = min(l_srcEyeshot.LeftTop.X, l_dstEyeshot.LeftTop.X);
		const long l_xmax = max(l_srcEyeshot.RightBottom.X, l_dstEyeshot.RightBottom.X);
		const long l_ymin = min(l_srcEyeshot.LeftTop.Y, l_dstEyeshot.LeftTop.Y);
		const long l_ymax = max(l_srcEyeshot.RightBottom.Y, l_dstEyeshot.RightBottom.Y);
		for (long y = l_ymin; y <= l_ymax; y++)
		{
			for(long x = l_xmin; x <= l_xmax; x++)
			{
				const long l_srcx = abs(x - l_src.X);
				const long l_srcy = abs(y - l_src.Y);
				const long l_dstx = abs(x - l_dst.X);
				const long l_dsty = abs(y - l_dst.Y);
				if (l_srcx <= GetEyeshotWidth() && l_srcy <= GetEyeshotWidth()
					&& l_dstx <= GetEyeshotWidth() && l_dsty <= GetEyeshotWidth()) //
					continue;
				else if ((l_srcx > GetEyeshotWidth() || l_srcy > GetEyeshotWidth())
					&& (l_dstx > GetEyeshotWidth() || l_dsty > GetEyeshotWidth())) //
					continue;
				else if (abs(x - l_src.X) <= GetEyeshotWidth() && abs(y - l_src.Y) <= GetEyeshotWidth()) //endsee
				{
					if (bActive)
						InactiveEyeshotCell(x, y);
					m_pCEyeshotCell[y][x].OutEyeshot(pCEnt);
				}
				else		//beginsee
				{
					if (bActive)
						ActiveEyeshotCell(x, y);
					m_pCEyeshotCell[y][x].EnterEyeshot(pCEnt);
				}
			}
		}

		//
		if (pCEnt->m_pCEyeshotHost)
		{
			//LG("", " %s [%d, %d] %s [%d, %d]\n", GetName(), l_dst.x, l_dst.y, pCEnt->GetLogName(), pCEnt->m_pCEyeshotHost->m_sPosX, pCEnt->m_pCEyeshotHost->m_sPosY);
			ToLogService("errors", LogLevel::Error, "(move)map {} from eyeshot cell[{}, {}] add entity {} find it is not break away foregone manage cell[{}, {}]", GetName(), l_dst.X, l_dst.Y, pCEnt->GetLogName(), pCEnt->m_pCEyeshotHost->m_sPosX, pCEnt->m_pCEyeshotHost->m_sPosY);
			return;
		}
		pCEnt->m_pCEyeshotHost = &m_pCEyeshotCell[l_dst.Y][l_dst.X];
		m_pCEyeshotCell[l_dst.Y][l_dst.X].AddEntity(pCEnt->IsCharacter());
	}
	tMoveEyeshot.End();

	tMoveArea.Begin();
	pCEnt->RefreshArea(&SrcPos);
	pCEnt->m_lastpos = STar;
	tMoveArea.End();

	DWORD	dwAllTime = tMoveState.GetTimeCount() + tMoveMMask.GetTimeCount() + tMoveEyeshot.GetTimeCount() + tMoveArea.GetTimeCount();
	if (dwAllTime >= 50)
		//LG("map_time", "\t\t[%s] time = %u%u%u%u%u\n",
		ToLogService("common", "\t\tcharacter[{}] eyeshot move spend overabundance time time = {}thereinto state spend {}explore spend {}eyeshot spend {}area spend {}",
			pCEnt->GetLogName(), dwAllTime, tMoveState.GetTimeCount(), tMoveMMask.GetTimeCount(), tMoveEyeshot.GetTimeCount(), tMoveArea.GetTimeCount());
}

void SubMap::LoadMonsterInfo(void)
{
}

// 
void SubMap::ClearSurfaceState(void)
{
	CStateCell		*pCStateCell;
	m_CStateCellL.BeginGet();
	while (pCStateCell = m_CStateCellL.GetNext())
	{
		pCStateCell->DropState(this);
	}
}

// 
void SubMap::ResetNotPlyCha()
{
	CCharacter	*pCCha;
	std::int32_t		lChaCount, lChaNum;
	CEyeshotCell	*pCEyeCell;
	for (int16_t y = 0; y < GetEyeshotCellLin(); y++)
	{
		for (int16_t x = 0; x < GetEyeshotCellCol(); x++)
		{
			pCEyeCell = &m_pCEyeshotCell[y][x];
			lChaCount = 0;
			lChaNum = pCEyeCell->GetChaNum();
			pCCha = pCEyeCell->m_pCChaL;

			while (pCCha)
			{
				if (++lChaCount > lChaNum)
				{
					//LG("", "[%d,%d] %d\n", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
					ToLogService("errors", LogLevel::Error, "eyeshot cell[{},{}] practice entity numbers{}", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
					break;
				}

				if (!pCCha->IsPlayerOwnCha())
					pCCha->Reset();

				if (pCCha->m_pCEyeshotCellNext)
					pCCha = pCCha->m_pCEyeshotCellNext->IsCharacter();
				else
					pCCha = 0;
			}
		}
	}
}

// 
void SubMap::ClearPlayerCha()
{
	CEyeshotCell	*pCEyeCell;
	CCharacter		*pCCha, *pCProcCha;
	long			lChaCount, lChaNum;
	//LG("enter_map", " %s %d!\n", GetName(), GetCopyNO());
	ToLogService("map", "map {}(copyID {}),start delete all character!", GetName(), GetCopyNO());
	m_CEyeshotCellL.BeginGet();
	while (pCEyeCell = m_CEyeshotCellL.GetNext())
	{
		lChaCount = 0;
		lChaNum = pCEyeCell->GetChaNum();
		pCCha = pCEyeCell->m_pCChaL;
		while (pCCha)
		{
			if (++lChaCount > lChaNum)
			{
				//LG("", "[%d,%d] %d\n", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
				ToLogService("errors", LogLevel::Error, "eyeshot cell[{},{}]practice entity numbers {}", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
				break;
			}

			pCProcCha = pCCha;
			if (pCCha->m_pCEyeshotCellNext)
				pCCha = pCCha->m_pCEyeshotCellNext->IsCharacter();
			else
				pCCha = 0;

			if(pCProcCha->IsPlayerFocusCha())
			{
				if (!pCProcCha->GetSubMap())
					//LG("", " %s(%s)[%d,%d] \n",
					ToLogService("errors", LogLevel::Error, "in the wind map notify character {}({})[{},{}] 's map is empty",
						pCProcCha->GetLogName(), pCProcCha->GetPlyCtrlCha()->GetLogName(), pCProcCha->GetPos().X, pCProcCha->GetPos().Y);

				//LG("enter_map", " %s  %s[%s]!\n", GetName(), pCProcCha->GetName(), pCProcCha->GetPlyMainCha()->GetName());
				ToLogService("map", "map {} closeclean out {}[{}]!", GetName(), pCProcCha->GetName(), pCProcCha->GetPlyMainCha()->GetName());
				if (!pCProcCha->IsLiveing())
				{
					g_luaAPI.Call("Relive", pCProcCha);

					pCProcCha->m_chSelRelive = enumEPLAYER_RELIVE_NONE;
					pCProcCha->m_chReliveLv = 0;
					pCProcCha->BackToCityEx(true);
				}
				else
					pCProcCha->BackToCityEx();
			}
		}
	}
	m_COutMapCha.Drop();
	//LG("enter_map", " %s %d !\n", GetName(), GetCopyNO());
	ToLogService("map", "map {}( copyID {})clean out character succeed!", GetName(), GetCopyNO());
}

void SubMap::ClearAllMonster(void)
{
	CCharacter	*pCCha;
	std::int32_t		lChaCount, lChaNum;
	CEyeshotCell	*pCEyeCell;
	for (int16_t y = 0; y < GetEyeshotCellLin(); y++)
	{
		for (int16_t x = 0; x < GetEyeshotCellCol(); x++)
		{
			pCEyeCell = &m_pCEyeshotCell[y][x];
			lChaCount = 0;
			lChaNum = pCEyeCell->GetChaNum();
			pCCha = pCEyeCell->m_pCChaL;

			while (pCCha)
			{
				if (++lChaCount > lChaNum)
				{
					//LG("", "[%d,%d] %d\n", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
					ToLogService("errors", LogLevel::Error, "eyeshot cell[{},{}]practice entity number {}", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
					break;
				}

				if (!pCCha->IsPlayerOwnCha())
					pCCha->ResetLifeTime(1000);

				if (pCCha->m_pCEyeshotCellNext)
					pCCha = pCCha->m_pCEyeshotCellNext->IsCharacter();
				else
					pCCha = 0;
			}
		}
	}
}

void SubMap::ClearAllMonsterByName(const char* szMonsName)
{
	CCharacter	*pCCha;
	std::int32_t		lChaCount, lChaNum;
	CEyeshotCell	*pCEyeCell;
	for (int16_t y = 0; y < GetEyeshotCellLin(); y++)
	{
		for (int16_t x = 0; x < GetEyeshotCellCol(); x++)
		{
			pCEyeCell = &m_pCEyeshotCell[y][x];
			lChaCount = 0;
			lChaNum = pCEyeCell->GetChaNum();
			pCCha = pCEyeCell->m_pCChaL;

			while (pCCha)
			{
				if (++lChaCount > lChaNum)
				{
					//LG("", "[%d,%d] %d\n", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
					ToLogService("errors", LogLevel::Error, "eyeshot cell[{},{}]practice entity number {}", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
					break;
				}

				if (!pCCha->IsPlayerOwnCha())
				{
					if (!strcmp(pCCha->GetName(), szMonsName))
						pCCha->ResetLifeTime(1000);
				}

				if (pCCha->m_pCEyeshotCellNext)
					pCCha = pCCha->m_pCEyeshotCellNext->IsCharacter();
				else
					pCCha = 0;
			}
		}
	}
}

void SubMap::ClearAllCha()
{
	CEyeshotCell	*pCEyeCell;
	CCharacter		*pCCha, *pCProcCha;
	long			lChaCount, lChaNum;
	//LG("enter_map", " %s %d!\n", GetName(), GetCopyNO());
	ToLogService("map", "map {}(copyID {})start clean out all monsters", GetName(), GetCopyNO());
	m_CEyeshotCellL.BeginGet();
	while (pCEyeCell = m_CEyeshotCellL.GetNext())
	{
		lChaCount = 0;
		lChaNum = pCEyeCell->GetChaNum();
		pCCha = pCEyeCell->m_pCChaL;
		while (pCCha)
		{
			if (++lChaCount > lChaNum)
			{
				//LG("", "[%d,%d] %d\n", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
				ToLogService("errors", LogLevel::Error, "eyeshot cell[{},{}]practice entity numbers {}", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
				break;
			}

			pCProcCha = pCCha;
			if (pCCha->m_pCEyeshotCellNext)
				pCCha = pCCha->m_pCEyeshotCellNext->IsCharacter();
			else
				pCCha = 0;

			if(!pCProcCha->IsPlayerFocusCha())
			{
				pCProcCha->Free();
			}
			else
			{
				if (!pCProcCha->GetSubMap())
					//LG("", " %s(%s)[%d,%d] \n",
					ToLogService("errors", LogLevel::Error, "in the wind map notify character {}({})[{},{}] 's map is empty",
					pCProcCha->GetLogName(), pCProcCha->GetPlyCtrlCha()->GetLogName(), pCProcCha->GetPos().X, pCProcCha->GetPos().Y);

				//LG("enter_map", " %s  %s[%s]!\n", GetName(), pCProcCha->GetName(), pCProcCha->GetPlyMainCha()->GetName());
				ToLogService("map", "map {} close,clean out character {}[{}]!", GetName(), pCProcCha->GetName(), pCProcCha->GetPlyMainCha()->GetName());
				if (!pCProcCha->IsLiveing())
				{
					g_luaAPI.Call("Relive", pCProcCha);

					pCProcCha->m_chSelRelive = enumEPLAYER_RELIVE_NONE;
					pCProcCha->m_chReliveLv = 0;
					pCProcCha->BackToCityEx(true);
				}
				else
					pCProcCha->BackToCityEx();
			}
		}
		pCEyeCell->m_pCChaL = NULL;
	}
	//LG("enter_map", " %s %d !\n", GetName(), GetCopyNO());
	ToLogService("map", "map {}(copyID {})clean out monster succeed!", GetName(), GetCopyNO());
}

void SubMap::EntryOpen()
{
	Open();
}

void SubMap::EntryClose()
{
}

void SubMap::Open()
{
	if (m_bIsRun)
		return;

	m_bIsRun = true;
}

void SubMap::Run(DWORD dwCurTime)
{
	if (!m_bIsRun)
		return;

	m_COutMapCha.Run(dwCurTime);

	if (m_timeScriptRun.IsOK(dwCurTime))
	{
		string	strScript = "map_copy_run_";
		strScript += GetName();
		g_luaAPI.Call(strScript.c_str(), this);
	}

	if (m_timeSpecialRun.IsOK(dwCurTime))
	{
		string	strScript = "map_copy_run_special_";
		strScript += GetName();
		g_luaAPI.Call(strScript.c_str(), this);

	}

}

void SubMap::Close()
{
	if (!m_bIsRun)
		return;
	string	strScript = "map_copy_before_close_";
	strScript += GetName();
	g_luaAPI.Call(strScript.c_str(), this);

	ClearSurfaceState();

	ClearPlayerCha();
	m_COutMapCha.Drop();
	ResetNotPlyCha();

	strScript = "map_copy_close_";
	strScript += GetName();
	g_luaAPI.Call(strScript.c_str(), this);

	m_bIsRun = false;
}

void SubMap::BeforePlyOutMap(CCharacter *pCCha)
{
	m_pCMapRes->SubEntryPlayer(GetCopyNO());

	string	strScript = "before_leave_";
	strScript += GetName();
	g_luaAPI.Call(strScript.c_str(), pCCha, this);
}

void SubMap::AfterPlyEnterMap(CCharacter *pCCha)
{
	string	strScript = "after_enter_";
	strScript += GetName();
	g_luaAPI.Call(strScript.c_str(), pCCha, this);
}

void SubMap::BeginGetPlyCha(void)
{
	m_CEyeshotCellL.BeginGet();
	CEyeshotCell	*pCEyeCell = m_CEyeshotCellL.GetCurrent();
	if (pCEyeCell)
		pCEyeCell->BeginGetCha();
}

CCharacter* SubMap::GetNextPlyCha(void)
{
	CCharacter	*pCCha = 0;

Research:
	CEyeshotCell	*pCEyeCell = m_CEyeshotCellL.GetCurrent();
	if (pCEyeCell)
	{
		pCCha = pCEyeCell->GetNextCha();
		while (!pCCha)
		{
			m_CEyeshotCellL.GetNext();
			pCEyeCell = m_CEyeshotCellL.GetCurrent();
			if (!pCEyeCell)
				break;
			pCEyeCell->BeginGetCha();
			pCCha = pCEyeCell->GetNextCha();
		}
	}
	if (pCCha)
		if (!pCCha->IsPlayerOwnCha())
			goto Research;

	return pCCha;
}

bool SubMap::CheckRun(void)
{
	if (IsRun())
		return true;
	if (!m_pCMapRes)
		return false;

	if (m_pCMapRes->GetCopyStartType() == enumMAPCOPY_START_CONDITION)
	{
		if (m_pCMapRes->GetCopyStartCdtType() == enumMAPCOPY_START_CDT_PLYNUM)
		{
			if (GetPlayerNum() >= m_pCMapRes->GetCopyStartCdtVal())
			{
				Open();

				string	strScript = "map_copy_first_run_";
				strScript += GetName();
				g_luaAPI.Call(strScript.c_str(), this);

				return true;
			}
		}
	}

	return false;
}

void SubMap::DealActivePlayer(string& function)
{
	CCharacter * pCha;
	BeginGetPlyCha();

	while(pCha = GetNextPlyCha())
	{
		if(pCha->IsPlayerCha() && pCha->IsLiveing())
		{
			g_luaAPI.Call(function.c_str(), pCha);
		}
	}


}

void SubMap::DealPlayer(string& function)
{
	CCharacter * pCha = NULL;
	BeginGetPlyCha();

	while(pCha = GetNextPlyCha())
	{
		if(pCha->IsPlayerCha())
		{
			g_luaAPI.Call(function.c_str(), pCha);
		}
	}
}

//=============================================================================
COutMapCha::COutMapCha(unsigned short usFreq)
{
	m_ulTick = GetTickCount();
	m_usFreq = usFreq;
}

COutMapCha::~COutMapCha()
{
	/*
	SMgrUnit	*pSCarrier;
	pSCarrier = m_pSExecQueue;
	while (pSCarrier)
	{
		m_pSExecQueue = pSCarrier->pSNext;
		delete pSCarrier;
		pSCarrier = m_pSExecQueue;
	}

	pSCarrier = m_pSFreeQueue;
	while (pSCarrier)
	{
		m_pSFreeQueue = pSCarrier->pSNext;
		delete pSCarrier;
		pSCarrier = m_pSFreeQueue;
	}

	*/
	spawnQueue.clear();
}

void COutMapCha::Add(CCharacter *pCObj, std::uint32_t	ulChaID, SSwitchMapInfo *pSwitchInfo, char chAction, std::int32_t lLeftTick1, std::int32_t lLeftTick2)
{
	if (!pCObj)
		return;

	auto pSCarrier = std::make_unique<SMgrUnit>();
	pSCarrier->pCCha = pCObj;
	pSCarrier->ulChaID = ulChaID;
	memcpy(&pSCarrier->SwitchInfo, pSwitchInfo, sizeof(SSwitchMapInfo));
	pSCarrier->chAction = chAction;
	pSCarrier->lLeftTick1 = lLeftTick1;
	pSCarrier->lLeftTick2 = lLeftTick2;
	pSCarrier->chStep = 1;

	spawnQueue.emplace_back(std::move(pSCarrier));
	
	// Spawn queue recoded - Mdr September 2020

}

void COutMapCha::Run(unsigned long ulCurTick)
{
	
	long	lTickDist = ulCurTick - m_ulTick;

	if (lTickDist < m_usFreq) {
	return;
	}
	m_ulTick = ulCurTick;

	spawnQueue.erase(
		std::remove_if(spawnQueue.begin(), spawnQueue.end(),
			[&](std::unique_ptr<SMgrUnit>& pSCarrier)
			{
				if (!pSCarrier)
				{
					return true;
				}

				if (!pSCarrier->IsValidCha())
				{
					return true;
				}

				switch (pSCarrier->chStep)
				{
				case 1:
				{
					pSCarrier->lLeftTick1 -= lTickDist;
					if (pSCarrier->lLeftTick1 <= 0)
					{
						ExecTimeCha(pSCarrier.get());
						return false;
					}
				}
				break;
				case 2:
				{
					pSCarrier->lLeftTick2 -= lTickDist;
					if (pSCarrier->lLeftTick2 <= 0)
					{
						ExecTimeCha(pSCarrier.get());
						return true;
					}
				}
				break;
				}

				return false;
			}
	), spawnQueue.end());

	//vector<SMgrUnit*>::iterator it = spawnQueue.begin();
	//int n = 0;
	//while (it != spawnQueue.end()) {
	//	it = spawnQueue.begin();
	//	SMgrUnit* pSCarrier = spawnQueue.at(n);
	//	
	//	if (!pSCarrier) 
	//	{
	//		it = spawnQueue.erase(it);
	//		continue;
	//	}
	//	if (!pSCarrier->IsValidCha()) 
	//	{
	//		it = spawnQueue.erase(it);
	//		continue;
	//	}
	//	if (pSCarrier->chStep == 1)
	//	{
	//		
	//		pSCarrier->lLeftTick1 -= lTickDist;
	//		if (pSCarrier->lLeftTick1 <= 0) {
	//			ExecTimeCha(pSCarrier);
	//			continue;
	//		}
	//	}
	//	else if (pSCarrier->chStep == 2)
	//	{
	//		pSCarrier->lLeftTick2 -= lTickDist;
	//		if (pSCarrier->lLeftTick2 <= 0) {
	//			ExecTimeCha(pSCarrier);
	//			it = spawnQueue.erase(it);
	//			continue;
	//		}
	//	}
	//	it++;
	//	n++;
	//}
	//
}

void COutMapCha::Drop()
{

	for (const auto& pSCarrier : spawnQueue)
	{
		if (pSCarrier)
		{
			ExecTimeCha(pSCarrier.get());
			ExecTimeCha(pSCarrier.get());
		}
	}
	spawnQueue.clear();

}

void COutMapCha::ExecTimeCha(SMgrUnit *pChaInfo)
{
	if (pChaInfo->chStep == 1)
	{
		pChaInfo->SwitchInfo.pSrcMap->GoOut(pChaInfo->pCCha);
		pChaInfo->pCCha->SetExistState(enumEXISTS_RESUMEING);
		pChaInfo->chStep++;
	}
	else if (pChaInfo->chStep == 2)
	{
		switch (pChaInfo->chAction)
		{
		case	enumCHA_TIMEER_ENTERMAP:
			{
				CCharacter	*pCCha = pChaInfo->pCCha;
				if (pCCha->IsPlayerCha()) // 
				{
					//LG("", " %s %s(%s)\n", pCCha->GetLogName(), pCCha->GetPlyMainCha()->GetLogName(), pCCha->GetPlyCtrlCha()->GetLogName());
					ToLogService("common", "monster name {}character player name {}({})", pCCha->GetLogName(), pCCha->GetPlyMainCha()->GetLogName(), pCCha->GetPlyCtrlCha()->GetLogName());
					break;
				}
				
				
				if(pCCha->GetLifeTime()!=0)
				{
					break;
				}

				pCCha->SetInOutMapQueue(false);
				pCCha->m_chSelRelive = enumEPLAYER_RELIVE_NONE;

				g_ulCurID = pCCha->GetID();
				g_lCurHandle = pCCha->GetHandle();

				pCCha->setAttr(ATTR_HP, pCCha->m_CChaAttr.GetAttr(ATTR_MXHP));	// HP
				pCCha->setAttr(ATTR_SP, pCCha->m_CChaAttr.GetAttr(ATTR_MXSP));	// SP
				//pCCha->m_timerScripts.Reset();
				pCCha->SetExistState(enumEXISTS_NATALITY);
				
				pCCha->SwitchMap(pChaInfo->SwitchInfo.pSrcMap, pChaInfo->SwitchInfo.szTarMapName, pChaInfo->SwitchInfo.STarPos.X, pChaInfo->SwitchInfo.STarPos.Y, false, enumSWITCHMAP_DIE, pChaInfo->SwitchInfo.pSrcMap->GetCopyNO());

				pCCha->ResetAIState();	// ai

				g_ulCurID = defINVALID_CHA_ID;
				g_lCurHandle = defINVALID_CHA_HANDLE;
			}
			break;
		}
		pChaInfo->chStep++;
	}
}

// ============================================================================
// Ранее inline-методы из SubMap.h, вынесены в .cpp 2026-04-22.
// ============================================================================

bool        SubMap::IsRun(void)       { return m_bIsRun; }
const char* SubMap::GetName(void)     { return m_pCMapRes->GetName(); }

bool SubMap::IsValidPos(std::int32_t lPosX, std::int32_t lPosY) {
	const Corsairs::Util::Rect& MapRange = GetRange();
	if (lPosX < MapRange.LeftTop.X || lPosX >= MapRange.RightBottom.X
		|| lPosY < MapRange.LeftTop.Y || lPosY >= MapRange.RightBottom.Y)
		return false;
	return true;
}

std::uint16_t SubMap::GetAreaAttr(std::int32_t lPosX, std::int32_t lPosY) {
	int16_t sUnitWidth, sUnitHeight;
	int16_t sUnitX, sUnitY;
	std::uint16_t usAreaAttr;

	m_pCMapRes->m_CTerrain.GetUnitSize(&sUnitWidth, &sUnitHeight);
	sUnitX = int16_t(lPosX / sUnitWidth);
	sUnitY = int16_t(lPosY / sUnitHeight);
	m_pCMapRes->m_CTerrain.GetUnitAttr(sUnitX, sUnitY, usAreaAttr);
	return usAreaAttr;
}

std::uint16_t SubMap::GetAreaAttr(const Corsairs::Util::Point& Pos) { return GetAreaAttr(Pos.X, Pos.Y); }

int16_t SubMap::GetEyeshotCellWidth(void) const  { return m_pCMapRes->m_csEyeshotCellWidth; }
int16_t SubMap::GetEyeshotCellHeight(void) const { return m_pCMapRes->m_csEyeshotCellHeight; }
int16_t SubMap::GetEyeshotCellLin(void) const    { return m_pCMapRes->m_sEyeshotCellLin; }
int16_t SubMap::GetEyeshotCellCol(void) const    { return m_pCMapRes->m_sEyeshotCellCol; }

int16_t SubMap::GetStateCellWidth(void) const    { return m_pCMapRes->m_csStateCellWidth; }
int16_t SubMap::GetStateCellHeight(void) const   { return m_pCMapRes->m_csStateCellHeight; }
int16_t SubMap::GetStateCellLin(void) const      { return m_pCMapRes->m_sStateCellLin; }
int16_t SubMap::GetStateCellCol(void) const      { return m_pCMapRes->m_sStateCellCol; }

int16_t SubMap::GetBlockCellWidth(void) const    { return m_pCMapRes->m_csBlockUnitWidth; }
int16_t SubMap::GetBlockCellHeight(void) const   { return m_pCMapRes->m_csBlockUnitHeight; }

bool SubMap::GetTerrainCellSize(int16_t* psWidth, int16_t* psHeight) {
	return m_pCMapRes->m_CTerrain.GetUnitSize(psWidth, psHeight);
}
bool SubMap::GetTerrainCellAttr(int16_t sUnitX, int16_t sUnitY, std::uint16_t& usAttribute) {
	return m_pCMapRes->m_CTerrain.GetUnitAttr(sUnitX, sUnitY, usAttribute);
}
bool SubMap::GetTerrainCellIsland(int16_t sUnitX, int16_t sUnitY, std::uint8_t& uchIsland) {
	return m_pCMapRes->m_CTerrain.GetUnitIsland(sUnitX, sUnitY, uchIsland);
}

BYTE SubMap::IsBlock(std::int32_t lCellX, std::int32_t lCellY) { return m_pCMapRes->m_CBlock.IsBlock(lCellX, lCellY); }

const Corsairs::Util::Rect& SubMap::GetRange(void) const { return m_pCMapRes->GetRange(); }

BYTE       SubMap::GetMapID()                  { return m_pCMapRes->GetMapID(); }
int16_t SubMap::GetEyeshotWidth(void) const { return m_pCMapRes->m_eyeshotwidth; }

bool       SubMap::CanPK(void)                 { return m_pCMapRes->CanPK(); }
bool       SubMap::CanSavePos(void)            { return m_pCMapRes->CanSavePos(); }

std::int32_t  SubMap::GetMonsterNum(void)         { return m_pCMapRes->m_pCMonsterSpawn->GetChaCount(); }

CMapRes*   SubMap::GetMapRes(void)             { return m_pCMapRes; }

void       SubMap::SetCopyNO(int16_t sCopyNO) { m_sCopyNO = sCopyNO; }
int16_t SubMap::GetCopyNO(void)             { return m_sCopyNO; }

std::int32_t  SubMap::GetPlayerNum(void)          { return m_lPlayerNum; }

std::int32_t SubMap::GetInfoParam(char chParamID) {
	if (chParamID < 0 || chParamID >= defMAPCOPY_INFO_PARAM_NUM) return 0;
	return m_lInfoParam[chParamID];
}
bool SubMap::SetInfoParam(char chParamID, std::int32_t lParamVal) {
	if (chParamID < 0 || chParamID >= defMAPCOPY_INFO_PARAM_NUM) return false;
	m_lInfoParam[chParamID] = lParamVal;
	return true;
}

void SubMap::SetSpecialInter(int interva) { m_timeSpecialRun.SetInterval(interva); }

std::int32_t SubMap::GetActivePlayer() {
	CCharacter* pCha;
	long lActivePlayerNum = 0;
	BeginGetPlyCha();

	while (pCha = GetNextPlyCha()) {
		if (pCha->IsPlayerCha() && pCha->IsLiveing()) {
			lActivePlayerNum++;
		}
	}
	return lActivePlayerNum;
}

void SubMap::ActiveEyeshotCell(std::int32_t lCellX, std::int32_t lCellY) {
	if (m_pCEyeshotCell[lCellY][lCellX].m_lActNum == 0)
		m_CEyeshotCellL.Add(&m_pCEyeshotCell[lCellY][lCellX]);
	m_pCEyeshotCell[lCellY][lCellX].m_lActNum++;
}

void SubMap::InactiveEyeshotCell(std::int32_t lCellX, std::int32_t lCellY) {
	m_pCEyeshotCell[lCellY][lCellX].m_lActNum--;
	if (m_pCEyeshotCell[lCellY][lCellX].m_lActNum == 0) {
		if (CountEyeshotPlyActiveNum(lCellX, lCellY) > 0) {
			m_pCEyeshotCell[lCellY][lCellX].m_lActNum++;
			ToLogService("errors", LogLevel::Error,
						 "when eyeshot cell[{},{}] stop activation, find the character player who has eyeshot ability.",
						 lCellX, lCellY);
		}
		else
			m_CEyeshotCellL.Del(&m_pCEyeshotCell[lCellY][lCellX]);
	}
}

bool SubMap::IsValidStateCell(std::int32_t x, std::int32_t y) {
	return _stateCellGrid.Get(static_cast<short>(x), static_cast<short>(y)) != nullptr;
}

CChaListNode* SubMap::StateCellAddCha(std::int32_t lCellX, std::int32_t lCellY, CCharacter* pCCha, bool bIn) {
	CheckStateCell(lCellX, lCellY);
	return _stateCellGrid.Get(static_cast<short>(lCellX), static_cast<short>(lCellY))->AddCharacter(pCCha, bIn);
}

void SubMap::StateCellDelCha(std::int32_t lCellX, std::int32_t lCellY, CChaListNode* pCChaNode) {
	_stateCellGrid.Get(static_cast<short>(lCellX), static_cast<short>(lCellY))->DelCharacter(pCChaNode);
	ReleaseStateCell(lCellX, lCellY);
}

void SubMap::ActiveStateCell(std::int32_t lCellX, std::int32_t lCellY) {
	auto* cell = _stateCellGrid.Get(static_cast<short>(lCellX), static_cast<short>(lCellY));
	if (cell->m_lActNum == 0) {
		m_CStateCellL.Add(cell);
	}
	cell->m_lActNum++;
	ActiveEyeshotCell(cell->m_pCEyeshotCell->m_sPosX, cell->m_pCEyeshotCell->m_sPosY);
}

void SubMap::InactiveStateCell(std::int32_t lCellX, std::int32_t lCellY) {
	auto* cell = _stateCellGrid.Get(static_cast<short>(lCellX), static_cast<short>(lCellY));
	InactiveEyeshotCell(cell->m_pCEyeshotCell->m_sPosX, cell->m_pCEyeshotCell->m_sPosY);
	cell->m_lActNum--;
	if (cell->m_lActNum == 0) {
		m_CStateCellL.Del(cell);
		ReleaseStateCell(lCellX, lCellY);
	}
}

bool SubMap::AddCellState(std::uint8_t uchFightID, std::uint32_t ulSrcWorldID, std::int32_t lSrcHandle, char chObjType,
						  char chObjHabitat, char chEffType,
						  std::int32_t lCellX, std::int32_t lCellY, std::uint8_t uchStateID, std::uint8_t uchStateLv,
						  std::uint32_t ulStartTick, std::int32_t lOnTick, char chType, char chWithCenter) {
	auto sx = static_cast<short>(lCellX);
	auto sy = static_cast<short>(lCellY);
	bool bValid = _stateCellGrid.Get(sx, sy) != nullptr;
	if (!bValid) {
		CheckStateCell(lCellX, lCellY);
	}
	auto* cell = _stateCellGrid.Get(sx, sy);
	bool bHasState = cell->HasState(uchStateID);
	bool bAddSuc = cell->AddState(uchFightID, ulSrcWorldID, lSrcHandle, chObjType,
								  chObjHabitat, chEffType, uchStateID, uchStateLv,
								  ulStartTick, lOnTick, chType, chWithCenter);
	if (!bValid && !bAddSuc) {
		ReleaseStateCell(lCellX, lCellY);
	}
	if (!bHasState && bAddSuc) {
		ActiveStateCell(lCellX, lCellY);
	}
	return bAddSuc;
}

void SubMap::ReleaseStateCell(std::int32_t x, std::int32_t y) {
	auto sx = static_cast<short>(x);
	auto sy = static_cast<short>(y);
	auto* cell = _stateCellGrid.Get(sx, sy);
	if (cell && cell->GetChaNum() == 0 && cell->GetStateNum() == 0) {
		g_pGameApp->m_MapStateCellPool.Release(cell);
		_stateCellGrid.Set(sx, sy, nullptr);
	}
}

void SubMap::CheckStateCell(std::int32_t x, std::int32_t y) {
	auto sx = static_cast<short>(x);
	auto sy = static_cast<short>(y);
	if (!_stateCellGrid.Get(sx, sy)) {
		auto* cell = g_pGameApp->m_MapStateCellPool.Get();
		cell->m_sPosX = sx;
		cell->m_sPosY = sy;
		cell->m_pCEyeshotCell = &m_pCEyeshotCell[y * GetStateCellWidth() / GetEyeshotCellWidth()][x *
			GetStateCellWidth() / GetEyeshotCellHeight()];
		_stateCellGrid.Set(sx, sy, cell);
	}
}

