/* Generated by Together */

#ifndef ENTITY_H
#define ENTITY_H

#include "App/GameAppNet.h"
#include "Entity/Event.h"
#include "Network/CompCommand.h"

#include <source_location>

class CCharacter;
class CMoveAble;
class CFightAble;
class CItem;
class Monster;
class CAttachable;
class CEventEntity;
class CStateCellNode;
class CStateCell;
class CChaListNode;
class CEyeshotCell;
struct SSkillStateUnit;

//using	namespace	GAME;

namespace mission {
	class CNpc;
	class CEventEntity;
};

#define defENTITY_NAME_LEN	32
#define defLOG_NAME_LEN		64

/**
 * @alias
 */
class Entity {
	friend class SubMap;
	friend class CMgrUnit;
	friend class GameServerApp;
	friend class CCharacter;
	friend class CMoveAble;
	friend class CAction;
	friend class CFightAble;
	friend class CGameApp;
	friend class CChaSpawn;
	friend class CMapSwitchEntitySpawn;

public:
	// DEBUG-сборка логирует каждый Free с адресом+именем+call-site (source_location).
	// Помогает ловить двойные освобождения, висячие entity в eyeshot и т.п.
	void Free(std::source_location loc = std::source_location::current());
	void Initially();
	// ВАЖНО: Finally virtual — Free() живёт в Entity и вызывает Finally()
	// через this; без virtual диспатч уходит в Entity::Finally, минуя
	// CItem::Finally/CCharacter::Finally (а именно они снимают entity
	// с карты через SubMap::GoOut). Если забыть virtual — item после
	// Free() остаётся в eyeshot-cell как dangling.
	virtual void Finally();

	void          SetInitShape(const Square& shape);
	const Square& GetShape() const;

	void          SetPos(const Point& pos);
	void          SetPos(dbc::Long lPosX, dbc::Long lPosY);
	const Point&  GetPos() const;

	void          SetRadius(const long& lRadius);
	const long&   GetRadius() const;

	dbc::uLong    GetID() const;
	short         GetCat() const;
	void          SetID(dbc::uLong ulID);
	void          SetCat(short sCat);

	void          SetHandle(dbc::Long lHandle);
	dbc::Long     GetHandle(void);

	SubMap*       GetSubMap() const;
	SubMap*       GetSubMapFar();
	void          SetSubMap(SubMap* pCMap);

	short         GetAngle() const;
	void          SetAngle(short sAngle);

	const Circle& GetTerritory();
	void          SetTerritory(Circle& STerritory);

	void NotiChgToEyeshot(Corsairs::Net::WPacket chginf, bool bIncludeOwn = true);

	void          SetLogName(const char* szName);
	const char*   GetLogName();

	// _name — std::string в UTF-8 (сервер и клиент мигрированы на UTF-8).
	// GetName() возвращает const char* для C-совместимости (strcmp/strncpy/
	// printf и т.п. работают как раньше). Для std::string-кода —
	// GetNameStr() возвращает const std::string&.
	void               SetName(const std::string& name);
	void               SetName(const char* name);
	const char*        GetName() const;
	const std::string& GetNameStr() const;

	void          SetBirthCity(dbc::cChar* cszName);
	const char*   GetBirthCity();

	void          SetBirthMap(dbc::cChar* cszName);
	const char*   GetBirthMap();

	void          SetWitherTime(dbc::Long lWitherTime);
	void          SetResumeTime(dbc::Long lResumeTime);

	void          SetEvent(CEvent& CEvt);
	CEvent&       GetEvent(void);

	virtual void Run(dbc::uLong ulCurTick);
	Entity* SearchByIDInEyeshot(dbc::cuLong culID);

	dbc::Short    GetExistState(void);
	void          SetExistState(dbc::Short sState);

	bool IsLiveing(void);

	dbc::Short    GetStopState(void);
	void          SetStopState(dbc::Short sState);

	bool          GetEyeshotAbility(void);
	void          SetEyeshotAbility(bool bEyeshot);

	void ActiveEyeshot(bool bActive = true);
	bool          IsValid(void);
	void          SetValid(bool bValid = true);

	dbc::uShort   GetAreaAttr(void);
	void          SetAreaAttr(dbc::uShort usAreaAttr);

	dbc::uChar    GetIslandID(void);
	void          SetIslandID(dbc::uChar uchIsland);

	bool          IsInSafeArea(void);

	CStateCellNode* EnterStateCell(CStateCell* pStateCell, CChaListNode* pEntiNode, bool bIsIn = false);
	void OutMgrUnit(CStateCellNode* pCMgrNode);
	void SetCenterMgrNode(CStateCellNode* pCMgrNode);
	SSkillStateUnit* GetAreaState(dbc::uChar uchStateID);
	void RefreshArea(void);
	void RefreshArea(Point* pSrcPos);
	dbc::Short GetEyeshotWidth(void);

	dbc::Short    GetEyeshotHeight(void);

	bool IsInEyeshot(Entity* pCTarEnti);

	//
	virtual void GotoMapUnit();

	virtual CFightAble*            IsFightAble();
	virtual CMoveAble*             IsMoveAble();
	virtual CItem*                 IsItem();
	virtual Monster*               IsMonster();
	virtual CCharacter*            IsCharacter();
	virtual CAttachable*           IsAttachable();
	virtual mission::CNpc*         IsNpc();
	virtual mission::CEventEntity* IsEvent();

	void          BeginSee(Entity* obj);
	void          EndSee(Entity* obj);

	void WriteEventInfo(Corsairs::Net::WPacket& pk);
	void SynEventInfo(void);

	char m_szLogName[defLOG_NAME_LEN];
	dbc::uLong m_ID;

protected:
	Entity();

	virtual void ReflectINFof(Entity* srcent, Corsairs::Net::WPacket chginf);

	virtual bool overlap(long& xdist, long& ydist);

private:
	virtual const Square& GetLapChkShape();

	virtual void OnBeginSee(Entity*);
	virtual void OnEndSee(Entity*);

	virtual void OnBeginSeen(CCharacter* pCCha) =0; //ToDo:
	virtual void OnEndSeen(CCharacter* pCCha) =0; //ToDo:
	virtual void AreaChange(void);

	bool EdgeOverlap(long& xdist, long& ydist);
	bool ObstacleOverlap(long& xdist, long& ydist);

public:
	bool m_bValid;

	dbc::Long m_lHandle;

	short m_cat;

	Point m_lastpos;
	Square m_shape;
	Circle m_STerritory; //
	short m_sAngle;
	/**
	 * @label
	 * @labelDirection forward*/
	SubMap* m_submap;
	CStateCellNode *m_pCStateCellHead, *m_pCStateCellTail; //
	struct {
		Entity* m_pCEyeshotCellNext;
		Entity* m_pCEyeshotCellLast;
		CEyeshotCell* m_pCEyeshotHost;
	};

	dbc::Char m_szBirthMap[MAX_MAPNAME_LENGTH];
	dbc::Char m_szBirthCity[MAX_MAPNAME_LENGTH];

	CEvent m_CEvent;

	struct SExistCtrl {
		dbc::Short sState; // CompCommand.h EExistState
		dbc::Short sStopState; // EExistState enumEXISTS_WAITINGenumEXISTS_SLEEPING

		//
		dbc::Long lWitherTime; //
		dbc::Long lResumeTime; //
		dbc::uLong ulTick;
		//
	};

	std::string _name; // UTF-8
	SExistCtrl m_SExistCtrl;
	bool m_bActiveEyeshot;

	dbc::uShort m_usAreaAttr[2]; // 01CompCommand.hEAreaMask
	dbc::uChar m_ucIslandID[2]; // 01
};

extern void NotiPkToWorld(Corsairs::Net::WPacket chginf);

#endif //OBJECT_H
